// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -package semaphore -source interfaces.go -destination interfaces_mock.go -self_package github.com/uber/cadence/service/matching/semaphore
//

// Package semaphore is a generated GoMock package.
package semaphore

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockManager) Acquire(ctx context.Context, ownerID string) (AcquireResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, ownerID)
	ret0, _ := ret[0].(AcquireResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockManagerMockRecorder) Acquire(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockManager)(nil).Acquire), ctx, ownerID)
}

// Identifier mocks base method.
func (m *MockManager) Identifier() Identifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identifier")
	ret0, _ := ret[0].(Identifier)
	return ret0
}

// Identifier indicates an expected call of Identifier.
func (mr *MockManagerMockRecorder) Identifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identifier", reflect.TypeOf((*MockManager)(nil).Identifier))
}

// Start mocks base method.
func (m *MockManager) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManager)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockManager) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockManager)(nil).Stop))
}

// MockSemaphoreRegistry is a mock of SemaphoreRegistry interface.
type MockSemaphoreRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSemaphoreRegistryMockRecorder
	isgomock struct{}
}

// MockSemaphoreRegistryMockRecorder is the mock recorder for MockSemaphoreRegistry.
type MockSemaphoreRegistryMockRecorder struct {
	mock *MockSemaphoreRegistry
}

// NewMockSemaphoreRegistry creates a new mock instance.
func NewMockSemaphoreRegistry(ctrl *gomock.Controller) *MockSemaphoreRegistry {
	mock := &MockSemaphoreRegistry{ctrl: ctrl}
	mock.recorder = &MockSemaphoreRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemaphoreRegistry) EXPECT() *MockSemaphoreRegistryMockRecorder {
	return m.recorder
}

// AllManagers mocks base method.
func (m *MockSemaphoreRegistry) AllManagers() []Manager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllManagers")
	ret0, _ := ret[0].([]Manager)
	return ret0
}

// AllManagers indicates an expected call of AllManagers.
func (mr *MockSemaphoreRegistryMockRecorder) AllManagers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllManagers", reflect.TypeOf((*MockSemaphoreRegistry)(nil).AllManagers))
}

// GetOrCreate mocks base method.
func (m *MockSemaphoreRegistry) GetOrCreate(id Identifier, create func() (Manager, error)) (Manager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", id, create)
	ret0, _ := ret[0].(Manager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockSemaphoreRegistryMockRecorder) GetOrCreate(id, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockSemaphoreRegistry)(nil).GetOrCreate), id, create)
}

// ManagerByIdentifier mocks base method.
func (m *MockSemaphoreRegistry) ManagerByIdentifier(id Identifier) (Manager, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManagerByIdentifier", id)
	ret0, _ := ret[0].(Manager)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ManagerByIdentifier indicates an expected call of ManagerByIdentifier.
func (mr *MockSemaphoreRegistryMockRecorder) ManagerByIdentifier(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManagerByIdentifier", reflect.TypeOf((*MockSemaphoreRegistry)(nil).ManagerByIdentifier), id)
}

// Unregister mocks base method.
func (m *MockSemaphoreRegistry) Unregister(mgr Manager) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unregister", mgr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Unregister indicates an expected call of Unregister.
func (mr *MockSemaphoreRegistryMockRecorder) Unregister(mgr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockSemaphoreRegistry)(nil).Unregister), mgr)
}
