// Code generated by gowrap. DO NOT EDIT.
// template: ../../../templates/thrift.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package thrift

import (
	context "context"

	history "github.com/uber/cadence/.gen/go/history"
	replicator "github.com/uber/cadence/.gen/go/replicator"
	shared "github.com/uber/cadence/.gen/go/shared"
	mapper "github.com/uber/cadence/common/types/mapper/thrift"
)

func (g ThriftHandler) CloseShard(ctx context.Context, Request *shared.CloseShardRequest) (err error) {
	err = g.h.CloseShard(ctx, mapper.ToHistoryCloseShardRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) DescribeHistoryHost(ctx context.Context, Request *shared.DescribeHistoryHostRequest) (dp1 *shared.DescribeHistoryHostResponse, err error) {
	response, err := g.h.DescribeHistoryHost(ctx, mapper.ToHistoryDescribeHistoryHostRequest(Request))
	return mapper.FromHistoryDescribeHistoryHostResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) DescribeMutableState(ctx context.Context, Request *history.DescribeMutableStateRequest) (dp1 *history.DescribeMutableStateResponse, err error) {
	response, err := g.h.DescribeMutableState(ctx, mapper.ToHistoryDescribeMutableStateRequest(Request))
	return mapper.FromHistoryDescribeMutableStateResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) DescribeQueue(ctx context.Context, Request *shared.DescribeQueueRequest) (dp1 *shared.DescribeQueueResponse, err error) {
	response, err := g.h.DescribeQueue(ctx, mapper.ToHistoryDescribeQueueRequest(Request))
	return mapper.FromHistoryDescribeQueueResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) DescribeWorkflowExecution(ctx context.Context, DescribeRequest *history.DescribeWorkflowExecutionRequest) (dp1 *shared.DescribeWorkflowExecutionResponse, err error) {
	response, err := g.h.DescribeWorkflowExecution(ctx, mapper.ToHistoryDescribeWorkflowExecutionRequest(DescribeRequest))
	return mapper.FromHistoryDescribeWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) GetCrossClusterTasks(ctx context.Context, Request *shared.GetCrossClusterTasksRequest) (gp1 *shared.GetCrossClusterTasksResponse, err error) {
	response, err := g.h.GetCrossClusterTasks(ctx, mapper.ToHistoryGetCrossClusterTasksRequest(Request))
	return mapper.FromHistoryGetCrossClusterTasksResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) GetDLQReplicationMessages(ctx context.Context, Request *replicator.GetDLQReplicationMessagesRequest) (gp1 *replicator.GetDLQReplicationMessagesResponse, err error) {
	response, err := g.h.GetDLQReplicationMessages(ctx, mapper.ToHistoryGetDLQReplicationMessagesRequest(Request))
	return mapper.FromHistoryGetDLQReplicationMessagesResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) GetFailoverInfo(ctx context.Context, Request *history.GetFailoverInfoRequest) (gp1 *history.GetFailoverInfoResponse, err error) {
	response, err := g.h.GetFailoverInfo(ctx, mapper.ToHistoryGetFailoverInfoRequest(Request))
	return mapper.FromHistoryGetFailoverInfoResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) GetMutableState(ctx context.Context, GetRequest *history.GetMutableStateRequest) (gp1 *history.GetMutableStateResponse, err error) {
	response, err := g.h.GetMutableState(ctx, mapper.ToHistoryGetMutableStateRequest(GetRequest))
	return mapper.FromHistoryGetMutableStateResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) GetReplicationMessages(ctx context.Context, Request *replicator.GetReplicationMessagesRequest) (gp1 *replicator.GetReplicationMessagesResponse, err error) {
	response, err := g.h.GetReplicationMessages(ctx, mapper.ToHistoryGetReplicationMessagesRequest(Request))
	return mapper.FromHistoryGetReplicationMessagesResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) MergeDLQMessages(ctx context.Context, Request *replicator.MergeDLQMessagesRequest) (mp1 *replicator.MergeDLQMessagesResponse, err error) {
	response, err := g.h.MergeDLQMessages(ctx, mapper.ToHistoryMergeDLQMessagesRequest(Request))
	return mapper.FromHistoryMergeDLQMessagesResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) NotifyFailoverMarkers(ctx context.Context, Request *history.NotifyFailoverMarkersRequest) (err error) {
	err = g.h.NotifyFailoverMarkers(ctx, mapper.ToHistoryNotifyFailoverMarkersRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) PollMutableState(ctx context.Context, PollRequest *history.PollMutableStateRequest) (pp1 *history.PollMutableStateResponse, err error) {
	response, err := g.h.PollMutableState(ctx, mapper.ToHistoryPollMutableStateRequest(PollRequest))
	return mapper.FromHistoryPollMutableStateResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) PurgeDLQMessages(ctx context.Context, Request *replicator.PurgeDLQMessagesRequest) (err error) {
	err = g.h.PurgeDLQMessages(ctx, mapper.ToHistoryPurgeDLQMessagesRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) QueryWorkflow(ctx context.Context, QueryRequest *history.QueryWorkflowRequest) (qp1 *history.QueryWorkflowResponse, err error) {
	response, err := g.h.QueryWorkflow(ctx, mapper.ToHistoryQueryWorkflowRequest(QueryRequest))
	return mapper.FromHistoryQueryWorkflowResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RatelimitUpdate(ctx context.Context, Request *history.RatelimitUpdateRequest) (rp1 *history.RatelimitUpdateResponse, err error) {
	response, err := g.h.RatelimitUpdate(ctx, mapper.ToHistoryRatelimitUpdateRequest(Request))
	return mapper.FromHistoryRatelimitUpdateResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) ReadDLQMessages(ctx context.Context, Request *replicator.ReadDLQMessagesRequest) (rp1 *replicator.ReadDLQMessagesResponse, err error) {
	response, err := g.h.ReadDLQMessages(ctx, mapper.ToHistoryReadDLQMessagesRequest(Request))
	return mapper.FromHistoryReadDLQMessagesResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) ReapplyEvents(ctx context.Context, ReapplyEventsRequest *history.ReapplyEventsRequest) (err error) {
	err = g.h.ReapplyEvents(ctx, mapper.ToHistoryReapplyEventsRequest(ReapplyEventsRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) RecordActivityTaskHeartbeat(ctx context.Context, HeartbeatRequest *history.RecordActivityTaskHeartbeatRequest) (rp1 *shared.RecordActivityTaskHeartbeatResponse, err error) {
	response, err := g.h.RecordActivityTaskHeartbeat(ctx, mapper.ToHistoryRecordActivityTaskHeartbeatRequest(HeartbeatRequest))
	return mapper.FromHistoryRecordActivityTaskHeartbeatResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RecordActivityTaskStarted(ctx context.Context, AddRequest *history.RecordActivityTaskStartedRequest) (rp1 *history.RecordActivityTaskStartedResponse, err error) {
	response, err := g.h.RecordActivityTaskStarted(ctx, mapper.ToHistoryRecordActivityTaskStartedRequest(AddRequest))
	return mapper.FromHistoryRecordActivityTaskStartedResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RecordChildExecutionCompleted(ctx context.Context, CompletionRequest *history.RecordChildExecutionCompletedRequest) (err error) {
	err = g.h.RecordChildExecutionCompleted(ctx, mapper.ToHistoryRecordChildExecutionCompletedRequest(CompletionRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) RecordDecisionTaskStarted(ctx context.Context, AddRequest *history.RecordDecisionTaskStartedRequest) (rp1 *history.RecordDecisionTaskStartedResponse, err error) {
	response, err := g.h.RecordDecisionTaskStarted(ctx, mapper.ToHistoryRecordDecisionTaskStartedRequest(AddRequest))
	return mapper.FromHistoryRecordDecisionTaskStartedResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RefreshWorkflowTasks(ctx context.Context, Request *history.RefreshWorkflowTasksRequest) (err error) {
	err = g.h.RefreshWorkflowTasks(ctx, mapper.ToHistoryRefreshWorkflowTasksRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) RemoveSignalMutableState(ctx context.Context, RemoveRequest *history.RemoveSignalMutableStateRequest) (err error) {
	err = g.h.RemoveSignalMutableState(ctx, mapper.ToHistoryRemoveSignalMutableStateRequest(RemoveRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) RemoveTask(ctx context.Context, Request *shared.RemoveTaskRequest) (err error) {
	err = g.h.RemoveTask(ctx, mapper.ToHistoryRemoveTaskRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) ReplicateEventsV2(ctx context.Context, ReplicateV2Request *history.ReplicateEventsV2Request) (err error) {
	err = g.h.ReplicateEventsV2(ctx, mapper.ToHistoryReplicateEventsV2Request(ReplicateV2Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) RequestCancelWorkflowExecution(ctx context.Context, CancelRequest *history.RequestCancelWorkflowExecutionRequest) (err error) {
	err = g.h.RequestCancelWorkflowExecution(ctx, mapper.ToHistoryRequestCancelWorkflowExecutionRequest(CancelRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) ResetQueue(ctx context.Context, Request *shared.ResetQueueRequest) (err error) {
	err = g.h.ResetQueue(ctx, mapper.ToHistoryResetQueueRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) ResetStickyTaskList(ctx context.Context, ResetRequest *history.ResetStickyTaskListRequest) (rp1 *history.ResetStickyTaskListResponse, err error) {
	response, err := g.h.ResetStickyTaskList(ctx, mapper.ToHistoryResetStickyTaskListRequest(ResetRequest))
	return mapper.FromHistoryResetStickyTaskListResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) ResetWorkflowExecution(ctx context.Context, ResetRequest *history.ResetWorkflowExecutionRequest) (rp1 *shared.ResetWorkflowExecutionResponse, err error) {
	response, err := g.h.ResetWorkflowExecution(ctx, mapper.ToHistoryResetWorkflowExecutionRequest(ResetRequest))
	return mapper.FromHistoryResetWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RespondActivityTaskCanceled(ctx context.Context, CanceledRequest *history.RespondActivityTaskCanceledRequest) (err error) {
	err = g.h.RespondActivityTaskCanceled(ctx, mapper.ToHistoryRespondActivityTaskCanceledRequest(CanceledRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) RespondActivityTaskCompleted(ctx context.Context, CompleteRequest *history.RespondActivityTaskCompletedRequest) (err error) {
	err = g.h.RespondActivityTaskCompleted(ctx, mapper.ToHistoryRespondActivityTaskCompletedRequest(CompleteRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) RespondActivityTaskFailed(ctx context.Context, FailRequest *history.RespondActivityTaskFailedRequest) (err error) {
	err = g.h.RespondActivityTaskFailed(ctx, mapper.ToHistoryRespondActivityTaskFailedRequest(FailRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) RespondCrossClusterTasksCompleted(ctx context.Context, Request *shared.RespondCrossClusterTasksCompletedRequest) (rp1 *shared.RespondCrossClusterTasksCompletedResponse, err error) {
	response, err := g.h.RespondCrossClusterTasksCompleted(ctx, mapper.ToHistoryRespondCrossClusterTasksCompletedRequest(Request))
	return mapper.FromHistoryRespondCrossClusterTasksCompletedResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RespondDecisionTaskCompleted(ctx context.Context, CompleteRequest *history.RespondDecisionTaskCompletedRequest) (rp1 *history.RespondDecisionTaskCompletedResponse, err error) {
	response, err := g.h.RespondDecisionTaskCompleted(ctx, mapper.ToHistoryRespondDecisionTaskCompletedRequest(CompleteRequest))
	return mapper.FromHistoryRespondDecisionTaskCompletedResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RespondDecisionTaskFailed(ctx context.Context, FailedRequest *history.RespondDecisionTaskFailedRequest) (err error) {
	err = g.h.RespondDecisionTaskFailed(ctx, mapper.ToHistoryRespondDecisionTaskFailedRequest(FailedRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) ScheduleDecisionTask(ctx context.Context, ScheduleRequest *history.ScheduleDecisionTaskRequest) (err error) {
	err = g.h.ScheduleDecisionTask(ctx, mapper.ToHistoryScheduleDecisionTaskRequest(ScheduleRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) SignalWithStartWorkflowExecution(ctx context.Context, SignalWithStartRequest *history.SignalWithStartWorkflowExecutionRequest) (sp1 *shared.StartWorkflowExecutionResponse, err error) {
	response, err := g.h.SignalWithStartWorkflowExecution(ctx, mapper.ToHistorySignalWithStartWorkflowExecutionRequest(SignalWithStartRequest))
	return mapper.FromHistorySignalWithStartWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) SignalWorkflowExecution(ctx context.Context, SignalRequest *history.SignalWorkflowExecutionRequest) (err error) {
	err = g.h.SignalWorkflowExecution(ctx, mapper.ToHistorySignalWorkflowExecutionRequest(SignalRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) StartWorkflowExecution(ctx context.Context, StartRequest *history.StartWorkflowExecutionRequest) (sp1 *shared.StartWorkflowExecutionResponse, err error) {
	response, err := g.h.StartWorkflowExecution(ctx, mapper.ToHistoryStartWorkflowExecutionRequest(StartRequest))
	return mapper.FromHistoryStartWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) SyncActivity(ctx context.Context, SyncActivityRequest *history.SyncActivityRequest) (err error) {
	err = g.h.SyncActivity(ctx, mapper.ToHistorySyncActivityRequest(SyncActivityRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) SyncShardStatus(ctx context.Context, SyncShardStatusRequest *history.SyncShardStatusRequest) (err error) {
	err = g.h.SyncShardStatus(ctx, mapper.ToHistorySyncShardStatusRequest(SyncShardStatusRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) TerminateWorkflowExecution(ctx context.Context, TerminateRequest *history.TerminateWorkflowExecutionRequest) (err error) {
	err = g.h.TerminateWorkflowExecution(ctx, mapper.ToHistoryTerminateWorkflowExecutionRequest(TerminateRequest))
	return mapper.FromError(err)
}
