// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/elasticsearch/client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package client -destination client_mock.go github.com/uber/cadence/common/elasticsearch/client Client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	bulk "github.com/uber/cadence/common/elasticsearch/bulk"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ClearScroll mocks base method.
func (m *MockClient) ClearScroll(ctx context.Context, scrollID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearScroll", ctx, scrollID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearScroll indicates an expected call of ClearScroll.
func (mr *MockClientMockRecorder) ClearScroll(ctx, scrollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearScroll", reflect.TypeOf((*MockClient)(nil).ClearScroll), ctx, scrollID)
}

// Count mocks base method.
func (m *MockClient) Count(ctx context.Context, index, body string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, index, body)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockClientMockRecorder) Count(ctx, index, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockClient)(nil).Count), ctx, index, body)
}

// CreateIndex mocks base method.
func (m *MockClient) CreateIndex(ctx context.Context, index string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", ctx, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockClientMockRecorder) CreateIndex(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockClient)(nil).CreateIndex), ctx, index)
}

// DeleteIndex mocks base method.
func (m *MockClient) DeleteIndex(ctx context.Context, indexName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndex", ctx, indexName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockClientMockRecorder) DeleteIndex(ctx, indexName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockClient)(nil).DeleteIndex), ctx, indexName)
}

// GetMappings mocks base method.
func (m *MockClient) GetMappings(ctx context.Context, indexName string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappings", ctx, indexName)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappings indicates an expected call of GetMappings.
func (mr *MockClientMockRecorder) GetMappings(ctx, indexName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappings", reflect.TypeOf((*MockClient)(nil).GetMappings), ctx, indexName)
}

// HasIndex mocks base method.
func (m *MockClient) HasIndex(ctx context.Context, indexName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasIndex", ctx, indexName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasIndex indicates an expected call of HasIndex.
func (mr *MockClientMockRecorder) HasIndex(ctx, indexName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasIndex", reflect.TypeOf((*MockClient)(nil).HasIndex), ctx, indexName)
}

// IsHealthy mocks base method.
func (m *MockClient) IsHealthy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockClientMockRecorder) IsHealthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockClient)(nil).IsHealthy), ctx)
}

// IsNotFoundError mocks base method.
func (m *MockClient) IsNotFoundError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNotFoundError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNotFoundError indicates an expected call of IsNotFoundError.
func (mr *MockClientMockRecorder) IsNotFoundError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNotFoundError", reflect.TypeOf((*MockClient)(nil).IsNotFoundError), err)
}

// LatestTemplate mocks base method.
func (m *MockClient) LatestTemplate() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestTemplate")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// LatestTemplate indicates an expected call of LatestTemplate.
func (mr *MockClientMockRecorder) LatestTemplate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestTemplate", reflect.TypeOf((*MockClient)(nil).LatestTemplate))
}

// MappingsFromTemplate mocks base method.
func (m *MockClient) MappingsFromTemplate(template []byte) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MappingsFromTemplate", template)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MappingsFromTemplate indicates an expected call of MappingsFromTemplate.
func (mr *MockClientMockRecorder) MappingsFromTemplate(template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MappingsFromTemplate", reflect.TypeOf((*MockClient)(nil).MappingsFromTemplate), template)
}

// PutIndexTemplate mocks base method.
func (m *MockClient) PutIndexTemplate(ctx context.Context, templateName string, template []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutIndexTemplate", ctx, templateName, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutIndexTemplate indicates an expected call of PutIndexTemplate.
func (mr *MockClientMockRecorder) PutIndexTemplate(ctx, templateName, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutIndexTemplate", reflect.TypeOf((*MockClient)(nil).PutIndexTemplate), ctx, templateName, template)
}

// PutMappings mocks base method.
func (m *MockClient) PutMappings(ctx context.Context, indexName string, mappings map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMappings", ctx, indexName, mappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutMappings indicates an expected call of PutMappings.
func (mr *MockClientMockRecorder) PutMappings(ctx, indexName, mappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMappings", reflect.TypeOf((*MockClient)(nil).PutMappings), ctx, indexName, mappings)
}

// RunBulkProcessor mocks base method.
func (m *MockClient) RunBulkProcessor(ctx context.Context, p *bulk.BulkProcessorParameters) (bulk.GenericBulkProcessor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunBulkProcessor", ctx, p)
	ret0, _ := ret[0].(bulk.GenericBulkProcessor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunBulkProcessor indicates an expected call of RunBulkProcessor.
func (mr *MockClientMockRecorder) RunBulkProcessor(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBulkProcessor", reflect.TypeOf((*MockClient)(nil).RunBulkProcessor), ctx, p)
}

// Scroll mocks base method.
func (m *MockClient) Scroll(ctx context.Context, index, body, scrollID string) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scroll", ctx, index, body, scrollID)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scroll indicates an expected call of Scroll.
func (mr *MockClientMockRecorder) Scroll(ctx, index, body, scrollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scroll", reflect.TypeOf((*MockClient)(nil).Scroll), ctx, index, body, scrollID)
}

// Search mocks base method.
func (m *MockClient) Search(ctx context.Context, index, body string) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, index, body)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockClientMockRecorder) Search(ctx, index, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockClient)(nil).Search), ctx, index, body)
}
