// Code generated by gowrap. DO NOT EDIT.
// template: ../../../templates/thrift.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package thrift

import (
	context "context"

	admin "github.com/uber/cadence/.gen/go/admin"
	replicator "github.com/uber/cadence/.gen/go/replicator"
	shared "github.com/uber/cadence/.gen/go/shared"
	mapper "github.com/uber/cadence/common/types/mapper/thrift"
)

func (g AdminHandler) AddSearchAttribute(ctx context.Context, Request *admin.AddSearchAttributeRequest) (err error) {
	err = g.h.AddSearchAttribute(ctx, mapper.ToAdminAddSearchAttributeRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) CloseShard(ctx context.Context, Request *shared.CloseShardRequest) (err error) {
	err = g.h.CloseShard(ctx, mapper.ToAdminCloseShardRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) DeleteWorkflow(ctx context.Context, Request *admin.AdminDeleteWorkflowRequest) (ap1 *admin.AdminDeleteWorkflowResponse, err error) {
	response, err := g.h.DeleteWorkflow(ctx, mapper.ToAdminDeleteWorkflowRequest(Request))
	return mapper.FromAdminDeleteWorkflowResponse(response), mapper.FromError(err)
}

func (g AdminHandler) DescribeCluster(ctx context.Context) (dp1 *admin.DescribeClusterResponse, err error) {
	response, err := g.h.DescribeCluster(ctx)
	return mapper.FromAdminDescribeClusterResponse(response), mapper.FromError(err)
}

func (g AdminHandler) DescribeHistoryHost(ctx context.Context, Request *shared.DescribeHistoryHostRequest) (dp1 *shared.DescribeHistoryHostResponse, err error) {
	response, err := g.h.DescribeHistoryHost(ctx, mapper.ToAdminDescribeHistoryHostRequest(Request))
	return mapper.FromAdminDescribeHistoryHostResponse(response), mapper.FromError(err)
}

func (g AdminHandler) DescribeQueue(ctx context.Context, Request *shared.DescribeQueueRequest) (dp1 *shared.DescribeQueueResponse, err error) {
	response, err := g.h.DescribeQueue(ctx, mapper.ToAdminDescribeQueueRequest(Request))
	return mapper.FromAdminDescribeQueueResponse(response), mapper.FromError(err)
}

func (g AdminHandler) DescribeShardDistribution(ctx context.Context, Request *shared.DescribeShardDistributionRequest) (dp1 *shared.DescribeShardDistributionResponse, err error) {
	response, err := g.h.DescribeShardDistribution(ctx, mapper.ToAdminDescribeShardDistributionRequest(Request))
	return mapper.FromAdminDescribeShardDistributionResponse(response), mapper.FromError(err)
}

func (g AdminHandler) DescribeWorkflowExecution(ctx context.Context, Request *admin.DescribeWorkflowExecutionRequest) (dp1 *admin.DescribeWorkflowExecutionResponse, err error) {
	response, err := g.h.DescribeWorkflowExecution(ctx, mapper.ToAdminDescribeWorkflowExecutionRequest(Request))
	return mapper.FromAdminDescribeWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetCrossClusterTasks(ctx context.Context, Request *shared.GetCrossClusterTasksRequest) (gp1 *shared.GetCrossClusterTasksResponse, err error) {
	response, err := g.h.GetCrossClusterTasks(ctx, mapper.ToAdminGetCrossClusterTasksRequest(Request))
	return mapper.FromAdminGetCrossClusterTasksResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetDLQReplicationMessages(ctx context.Context, Request *replicator.GetDLQReplicationMessagesRequest) (gp1 *replicator.GetDLQReplicationMessagesResponse, err error) {
	response, err := g.h.GetDLQReplicationMessages(ctx, mapper.ToAdminGetDLQReplicationMessagesRequest(Request))
	return mapper.FromAdminGetDLQReplicationMessagesResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetDomainAsyncWorkflowConfiguraton(ctx context.Context, Request *admin.GetDomainAsyncWorkflowConfiguratonRequest) (gp1 *admin.GetDomainAsyncWorkflowConfiguratonResponse, err error) {
	response, err := g.h.GetDomainAsyncWorkflowConfiguraton(ctx, mapper.ToAdminGetDomainAsyncWorkflowConfiguratonRequest(Request))
	return mapper.FromAdminGetDomainAsyncWorkflowConfiguratonResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetDomainIsolationGroups(ctx context.Context, Request *admin.GetDomainIsolationGroupsRequest) (gp1 *admin.GetDomainIsolationGroupsResponse, err error) {
	response, err := g.h.GetDomainIsolationGroups(ctx, mapper.ToAdminGetDomainIsolationGroupsRequest(Request))
	return mapper.FromAdminGetDomainIsolationGroupsResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetDomainReplicationMessages(ctx context.Context, Request *replicator.GetDomainReplicationMessagesRequest) (gp1 *replicator.GetDomainReplicationMessagesResponse, err error) {
	response, err := g.h.GetDomainReplicationMessages(ctx, mapper.ToAdminGetDomainReplicationMessagesRequest(Request))
	return mapper.FromAdminGetDomainReplicationMessagesResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetDynamicConfig(ctx context.Context, Request *admin.GetDynamicConfigRequest) (gp1 *admin.GetDynamicConfigResponse, err error) {
	response, err := g.h.GetDynamicConfig(ctx, mapper.ToAdminGetDynamicConfigRequest(Request))
	return mapper.FromAdminGetDynamicConfigResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetGlobalIsolationGroups(ctx context.Context, Request *admin.GetGlobalIsolationGroupsRequest) (gp1 *admin.GetGlobalIsolationGroupsResponse, err error) {
	response, err := g.h.GetGlobalIsolationGroups(ctx, mapper.ToAdminGetGlobalIsolationGroupsRequest(Request))
	return mapper.FromAdminGetGlobalIsolationGroupsResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetOperationalDynamicConfig(ctx context.Context, Request *admin.GetOperationalDynamicConfigRequest) (gp1 *admin.GetOperationalDynamicConfigResponse, err error) {
	response, err := g.h.GetOperationalDynamicConfig(ctx, mapper.ToAdminGetOperationalDynamicConfigRequest(Request))
	return mapper.FromAdminGetOperationalDynamicConfigResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetReplicationMessages(ctx context.Context, Request *replicator.GetReplicationMessagesRequest) (gp1 *replicator.GetReplicationMessagesResponse, err error) {
	response, err := g.h.GetReplicationMessages(ctx, mapper.ToAdminGetReplicationMessagesRequest(Request))
	return mapper.FromAdminGetReplicationMessagesResponse(response), mapper.FromError(err)
}

func (g AdminHandler) GetWorkflowExecutionRawHistoryV2(ctx context.Context, GetRequest *admin.GetWorkflowExecutionRawHistoryV2Request) (gp1 *admin.GetWorkflowExecutionRawHistoryV2Response, err error) {
	response, err := g.h.GetWorkflowExecutionRawHistoryV2(ctx, mapper.ToAdminGetWorkflowExecutionRawHistoryV2Request(GetRequest))
	return mapper.FromAdminGetWorkflowExecutionRawHistoryV2Response(response), mapper.FromError(err)
}

func (g AdminHandler) ListDynamicConfig(ctx context.Context, Request *admin.ListDynamicConfigRequest) (lp1 *admin.ListDynamicConfigResponse, err error) {
	response, err := g.h.ListDynamicConfig(ctx, mapper.ToAdminListDynamicConfigRequest(Request))
	return mapper.FromAdminListDynamicConfigResponse(response), mapper.FromError(err)
}

func (g AdminHandler) ListOperationalDynamicConfig(ctx context.Context, Request *admin.ListOperationalDynamicConfigRequest) (lp1 *admin.ListOperationalDynamicConfigResponse, err error) {
	response, err := g.h.ListOperationalDynamicConfig(ctx, mapper.ToAdminListOperationalDynamicConfigRequest(Request))
	return mapper.FromAdminListOperationalDynamicConfigResponse(response), mapper.FromError(err)
}

func (g AdminHandler) MaintainCorruptWorkflow(ctx context.Context, Request *admin.AdminMaintainWorkflowRequest) (ap1 *admin.AdminMaintainWorkflowResponse, err error) {
	response, err := g.h.MaintainCorruptWorkflow(ctx, mapper.ToAdminMaintainCorruptWorkflowRequest(Request))
	return mapper.FromAdminMaintainCorruptWorkflowResponse(response), mapper.FromError(err)
}

func (g AdminHandler) MergeDLQMessages(ctx context.Context, Request *replicator.MergeDLQMessagesRequest) (mp1 *replicator.MergeDLQMessagesResponse, err error) {
	response, err := g.h.MergeDLQMessages(ctx, mapper.ToAdminMergeDLQMessagesRequest(Request))
	return mapper.FromAdminMergeDLQMessagesResponse(response), mapper.FromError(err)
}

func (g AdminHandler) PurgeDLQMessages(ctx context.Context, Request *replicator.PurgeDLQMessagesRequest) (err error) {
	err = g.h.PurgeDLQMessages(ctx, mapper.ToAdminPurgeDLQMessagesRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) ReadDLQMessages(ctx context.Context, Request *replicator.ReadDLQMessagesRequest) (rp1 *replicator.ReadDLQMessagesResponse, err error) {
	response, err := g.h.ReadDLQMessages(ctx, mapper.ToAdminReadDLQMessagesRequest(Request))
	return mapper.FromAdminReadDLQMessagesResponse(response), mapper.FromError(err)
}

func (g AdminHandler) ReapplyEvents(ctx context.Context, ReapplyEventsRequest *shared.ReapplyEventsRequest) (err error) {
	err = g.h.ReapplyEvents(ctx, mapper.ToAdminReapplyEventsRequest(ReapplyEventsRequest))
	return mapper.FromError(err)
}

func (g AdminHandler) RefreshWorkflowTasks(ctx context.Context, Request *shared.RefreshWorkflowTasksRequest) (err error) {
	err = g.h.RefreshWorkflowTasks(ctx, mapper.ToAdminRefreshWorkflowTasksRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) RemoveTask(ctx context.Context, Request *shared.RemoveTaskRequest) (err error) {
	err = g.h.RemoveTask(ctx, mapper.ToAdminRemoveTaskRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) ResendReplicationTasks(ctx context.Context, Request *admin.ResendReplicationTasksRequest) (err error) {
	err = g.h.ResendReplicationTasks(ctx, mapper.ToAdminResendReplicationTasksRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) ResetQueue(ctx context.Context, Request *shared.ResetQueueRequest) (err error) {
	err = g.h.ResetQueue(ctx, mapper.ToAdminResetQueueRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) RespondCrossClusterTasksCompleted(ctx context.Context, Request *shared.RespondCrossClusterTasksCompletedRequest) (rp1 *shared.RespondCrossClusterTasksCompletedResponse, err error) {
	response, err := g.h.RespondCrossClusterTasksCompleted(ctx, mapper.ToAdminRespondCrossClusterTasksCompletedRequest(Request))
	return mapper.FromAdminRespondCrossClusterTasksCompletedResponse(response), mapper.FromError(err)
}

func (g AdminHandler) RestoreDynamicConfig(ctx context.Context, Request *admin.RestoreDynamicConfigRequest) (err error) {
	err = g.h.RestoreDynamicConfig(ctx, mapper.ToAdminRestoreDynamicConfigRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) RestoreOperationalDynamicConfig(ctx context.Context, Request *admin.RestoreOperationalDynamicConfigRequest) (err error) {
	err = g.h.RestoreOperationalDynamicConfig(ctx, mapper.ToAdminRestoreOperationalDynamicConfigRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) UpdateDomainAsyncWorkflowConfiguraton(ctx context.Context, Request *admin.UpdateDomainAsyncWorkflowConfiguratonRequest) (up1 *admin.UpdateDomainAsyncWorkflowConfiguratonResponse, err error) {
	response, err := g.h.UpdateDomainAsyncWorkflowConfiguraton(ctx, mapper.ToAdminUpdateDomainAsyncWorkflowConfiguratonRequest(Request))
	return mapper.FromAdminUpdateDomainAsyncWorkflowConfiguratonResponse(response), mapper.FromError(err)
}

func (g AdminHandler) UpdateDomainIsolationGroups(ctx context.Context, Request *admin.UpdateDomainIsolationGroupsRequest) (up1 *admin.UpdateDomainIsolationGroupsResponse, err error) {
	response, err := g.h.UpdateDomainIsolationGroups(ctx, mapper.ToAdminUpdateDomainIsolationGroupsRequest(Request))
	return mapper.FromAdminUpdateDomainIsolationGroupsResponse(response), mapper.FromError(err)
}

func (g AdminHandler) UpdateDynamicConfig(ctx context.Context, Request *admin.UpdateDynamicConfigRequest) (err error) {
	err = g.h.UpdateDynamicConfig(ctx, mapper.ToAdminUpdateDynamicConfigRequest(Request))
	return mapper.FromError(err)
}

func (g AdminHandler) UpdateGlobalIsolationGroups(ctx context.Context, Request *admin.UpdateGlobalIsolationGroupsRequest) (up1 *admin.UpdateGlobalIsolationGroupsResponse, err error) {
	response, err := g.h.UpdateGlobalIsolationGroups(ctx, mapper.ToAdminUpdateGlobalIsolationGroupsRequest(Request))
	return mapper.FromAdminUpdateGlobalIsolationGroupsResponse(response), mapper.FromError(err)
}

func (g AdminHandler) UpdateOperationalDynamicConfig(ctx context.Context, Request *admin.UpdateOperationalDynamicConfigRequest) (err error) {
	err = g.h.UpdateOperationalDynamicConfig(ctx, mapper.ToAdminUpdateOperationalDynamicConfigRequest(Request))
	return mapper.FromError(err)
}
