// Code generated by gowrap. DO NOT EDIT.
// template: ../../../templates/thrift.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package thrift

import (
	context "context"

	shared "github.com/uber/cadence/.gen/go/shared"
	mapper "github.com/uber/cadence/common/types/mapper/thrift"
)

func (g APIHandler) BackfillSchedule(ctx context.Context, Request *shared.BackfillScheduleRequest) (bp1 *shared.BackfillScheduleResponse, err error) {
	response, err := g.h.BackfillSchedule(ctx, mapper.ToBackfillScheduleRequest(Request))
	return mapper.FromBackfillScheduleResponse(response), mapper.FromError(err)
}

func (g APIHandler) CountWorkflowExecutions(ctx context.Context, CountRequest *shared.CountWorkflowExecutionsRequest) (cp1 *shared.CountWorkflowExecutionsResponse, err error) {
	response, err := g.h.CountWorkflowExecutions(ctx, mapper.ToCountWorkflowExecutionsRequest(CountRequest))
	return mapper.FromCountWorkflowExecutionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) CreateSchedule(ctx context.Context, Request *shared.CreateScheduleRequest) (cp1 *shared.CreateScheduleResponse, err error) {
	response, err := g.h.CreateSchedule(ctx, mapper.ToCreateScheduleRequest(Request))
	return mapper.FromCreateScheduleResponse(response), mapper.FromError(err)
}

func (g APIHandler) DeleteDomain(ctx context.Context, DeleteRequest *shared.DeleteDomainRequest) (err error) {
	err = g.h.DeleteDomain(ctx, mapper.ToDeleteDomainRequest(DeleteRequest))
	return mapper.FromError(err)
}

func (g APIHandler) DeleteSchedule(ctx context.Context, Request *shared.DeleteScheduleRequest) (dp1 *shared.DeleteScheduleResponse, err error) {
	response, err := g.h.DeleteSchedule(ctx, mapper.ToDeleteScheduleRequest(Request))
	return mapper.FromDeleteScheduleResponse(response), mapper.FromError(err)
}

func (g APIHandler) DeprecateDomain(ctx context.Context, DeprecateRequest *shared.DeprecateDomainRequest) (err error) {
	err = g.h.DeprecateDomain(ctx, mapper.ToDeprecateDomainRequest(DeprecateRequest))
	return mapper.FromError(err)
}

func (g APIHandler) DescribeDomain(ctx context.Context, DescribeRequest *shared.DescribeDomainRequest) (dp1 *shared.DescribeDomainResponse, err error) {
	response, err := g.h.DescribeDomain(ctx, mapper.ToDescribeDomainRequest(DescribeRequest))
	return mapper.FromDescribeDomainResponse(response), mapper.FromError(err)
}

func (g APIHandler) DescribeSchedule(ctx context.Context, Request *shared.DescribeScheduleRequest) (dp1 *shared.DescribeScheduleResponse, err error) {
	response, err := g.h.DescribeSchedule(ctx, mapper.ToDescribeScheduleRequest(Request))
	return mapper.FromDescribeScheduleResponse(response), mapper.FromError(err)
}

func (g APIHandler) DescribeTaskList(ctx context.Context, Request *shared.DescribeTaskListRequest) (dp1 *shared.DescribeTaskListResponse, err error) {
	response, err := g.h.DescribeTaskList(ctx, mapper.ToDescribeTaskListRequest(Request))
	return mapper.FromDescribeTaskListResponse(response), mapper.FromError(err)
}

func (g APIHandler) DescribeWorkflowExecution(ctx context.Context, DescribeRequest *shared.DescribeWorkflowExecutionRequest) (dp1 *shared.DescribeWorkflowExecutionResponse, err error) {
	response, err := g.h.DescribeWorkflowExecution(ctx, mapper.ToDescribeWorkflowExecutionRequest(DescribeRequest))
	return mapper.FromDescribeWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g APIHandler) DiagnoseWorkflowExecution(ctx context.Context, DiagnoseRequest *shared.DiagnoseWorkflowExecutionRequest) (dp1 *shared.DiagnoseWorkflowExecutionResponse, err error) {
	response, err := g.h.DiagnoseWorkflowExecution(ctx, mapper.ToDiagnoseWorkflowExecutionRequest(DiagnoseRequest))
	return mapper.FromDiagnoseWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g APIHandler) FailoverDomain(ctx context.Context, FailoverRequest *shared.FailoverDomainRequest) (fp1 *shared.FailoverDomainResponse, err error) {
	response, err := g.h.FailoverDomain(ctx, mapper.ToFailoverDomainRequest(FailoverRequest))
	return mapper.FromFailoverDomainResponse(response), mapper.FromError(err)
}

func (g APIHandler) GetClusterInfo(ctx context.Context) (cp1 *shared.ClusterInfo, err error) {
	response, err := g.h.GetClusterInfo(ctx)
	return mapper.FromGetClusterInfoResponse(response), mapper.FromError(err)
}

func (g APIHandler) GetSearchAttributes(ctx context.Context) (gp1 *shared.GetSearchAttributesResponse, err error) {
	response, err := g.h.GetSearchAttributes(ctx)
	return mapper.FromGetSearchAttributesResponse(response), mapper.FromError(err)
}

func (g APIHandler) GetTaskListsByDomain(ctx context.Context, Request *shared.GetTaskListsByDomainRequest) (gp1 *shared.GetTaskListsByDomainResponse, err error) {
	response, err := g.h.GetTaskListsByDomain(ctx, mapper.ToGetTaskListsByDomainRequest(Request))
	return mapper.FromGetTaskListsByDomainResponse(response), mapper.FromError(err)
}

func (g APIHandler) GetWorkflowExecutionHistory(ctx context.Context, GetRequest *shared.GetWorkflowExecutionHistoryRequest) (gp1 *shared.GetWorkflowExecutionHistoryResponse, err error) {
	response, err := g.h.GetWorkflowExecutionHistory(ctx, mapper.ToGetWorkflowExecutionHistoryRequest(GetRequest))
	return mapper.FromGetWorkflowExecutionHistoryResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListArchivedWorkflowExecutions(ctx context.Context, ListRequest *shared.ListArchivedWorkflowExecutionsRequest) (lp1 *shared.ListArchivedWorkflowExecutionsResponse, err error) {
	response, err := g.h.ListArchivedWorkflowExecutions(ctx, mapper.ToListArchivedWorkflowExecutionsRequest(ListRequest))
	return mapper.FromListArchivedWorkflowExecutionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListClosedWorkflowExecutions(ctx context.Context, ListRequest *shared.ListClosedWorkflowExecutionsRequest) (lp1 *shared.ListClosedWorkflowExecutionsResponse, err error) {
	response, err := g.h.ListClosedWorkflowExecutions(ctx, mapper.ToListClosedWorkflowExecutionsRequest(ListRequest))
	return mapper.FromListClosedWorkflowExecutionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListDomains(ctx context.Context, ListRequest *shared.ListDomainsRequest) (lp1 *shared.ListDomainsResponse, err error) {
	response, err := g.h.ListDomains(ctx, mapper.ToListDomainsRequest(ListRequest))
	return mapper.FromListDomainsResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListFailoverHistory(ctx context.Context, ListRequest *shared.ListFailoverHistoryRequest) (lp1 *shared.ListFailoverHistoryResponse, err error) {
	response, err := g.h.ListFailoverHistory(ctx, mapper.ToListFailoverHistoryRequest(ListRequest))
	return mapper.FromListFailoverHistoryResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListOpenWorkflowExecutions(ctx context.Context, ListRequest *shared.ListOpenWorkflowExecutionsRequest) (lp1 *shared.ListOpenWorkflowExecutionsResponse, err error) {
	response, err := g.h.ListOpenWorkflowExecutions(ctx, mapper.ToListOpenWorkflowExecutionsRequest(ListRequest))
	return mapper.FromListOpenWorkflowExecutionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListSchedules(ctx context.Context, Request *shared.ListSchedulesRequest) (lp1 *shared.ListSchedulesResponse, err error) {
	response, err := g.h.ListSchedules(ctx, mapper.ToListSchedulesRequest(Request))
	return mapper.FromListSchedulesResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListTaskListPartitions(ctx context.Context, Request *shared.ListTaskListPartitionsRequest) (lp1 *shared.ListTaskListPartitionsResponse, err error) {
	response, err := g.h.ListTaskListPartitions(ctx, mapper.ToListTaskListPartitionsRequest(Request))
	return mapper.FromListTaskListPartitionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) ListWorkflowExecutions(ctx context.Context, ListRequest *shared.ListWorkflowExecutionsRequest) (lp1 *shared.ListWorkflowExecutionsResponse, err error) {
	response, err := g.h.ListWorkflowExecutions(ctx, mapper.ToListWorkflowExecutionsRequest(ListRequest))
	return mapper.FromListWorkflowExecutionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) PauseSchedule(ctx context.Context, Request *shared.PauseScheduleRequest) (pp1 *shared.PauseScheduleResponse, err error) {
	response, err := g.h.PauseSchedule(ctx, mapper.ToPauseScheduleRequest(Request))
	return mapper.FromPauseScheduleResponse(response), mapper.FromError(err)
}

func (g APIHandler) PollForActivityTask(ctx context.Context, PollRequest *shared.PollForActivityTaskRequest) (pp1 *shared.PollForActivityTaskResponse, err error) {
	response, err := g.h.PollForActivityTask(ctx, mapper.ToPollForActivityTaskRequest(PollRequest))
	return mapper.FromPollForActivityTaskResponse(response), mapper.FromError(err)
}

func (g APIHandler) PollForDecisionTask(ctx context.Context, PollRequest *shared.PollForDecisionTaskRequest) (pp1 *shared.PollForDecisionTaskResponse, err error) {
	response, err := g.h.PollForDecisionTask(ctx, mapper.ToPollForDecisionTaskRequest(PollRequest))
	return mapper.FromPollForDecisionTaskResponse(response), mapper.FromError(err)
}

func (g APIHandler) QueryWorkflow(ctx context.Context, QueryRequest *shared.QueryWorkflowRequest) (qp1 *shared.QueryWorkflowResponse, err error) {
	response, err := g.h.QueryWorkflow(ctx, mapper.ToQueryWorkflowRequest(QueryRequest))
	return mapper.FromQueryWorkflowResponse(response), mapper.FromError(err)
}

func (g APIHandler) RecordActivityTaskHeartbeat(ctx context.Context, HeartbeatRequest *shared.RecordActivityTaskHeartbeatRequest) (rp1 *shared.RecordActivityTaskHeartbeatResponse, err error) {
	response, err := g.h.RecordActivityTaskHeartbeat(ctx, mapper.ToRecordActivityTaskHeartbeatRequest(HeartbeatRequest))
	return mapper.FromRecordActivityTaskHeartbeatResponse(response), mapper.FromError(err)
}

func (g APIHandler) RecordActivityTaskHeartbeatByID(ctx context.Context, HeartbeatRequest *shared.RecordActivityTaskHeartbeatByIDRequest) (rp1 *shared.RecordActivityTaskHeartbeatResponse, err error) {
	response, err := g.h.RecordActivityTaskHeartbeatByID(ctx, mapper.ToRecordActivityTaskHeartbeatByIDRequest(HeartbeatRequest))
	return mapper.FromRecordActivityTaskHeartbeatByIDResponse(response), mapper.FromError(err)
}

func (g APIHandler) RefreshWorkflowTasks(ctx context.Context, Request *shared.RefreshWorkflowTasksRequest) (err error) {
	err = g.h.RefreshWorkflowTasks(ctx, mapper.ToRefreshWorkflowTasksRequest(Request))
	return mapper.FromError(err)
}

func (g APIHandler) RegisterDomain(ctx context.Context, RegisterRequest *shared.RegisterDomainRequest) (err error) {
	err = g.h.RegisterDomain(ctx, mapper.ToRegisterDomainRequest(RegisterRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RequestCancelWorkflowExecution(ctx context.Context, CancelRequest *shared.RequestCancelWorkflowExecutionRequest) (err error) {
	err = g.h.RequestCancelWorkflowExecution(ctx, mapper.ToRequestCancelWorkflowExecutionRequest(CancelRequest))
	return mapper.FromError(err)
}

func (g APIHandler) ResetStickyTaskList(ctx context.Context, ResetRequest *shared.ResetStickyTaskListRequest) (rp1 *shared.ResetStickyTaskListResponse, err error) {
	response, err := g.h.ResetStickyTaskList(ctx, mapper.ToResetStickyTaskListRequest(ResetRequest))
	return mapper.FromResetStickyTaskListResponse(response), mapper.FromError(err)
}

func (g APIHandler) ResetWorkflowExecution(ctx context.Context, ResetRequest *shared.ResetWorkflowExecutionRequest) (rp1 *shared.ResetWorkflowExecutionResponse, err error) {
	response, err := g.h.ResetWorkflowExecution(ctx, mapper.ToResetWorkflowExecutionRequest(ResetRequest))
	return mapper.FromResetWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g APIHandler) RespondActivityTaskCanceled(ctx context.Context, CanceledRequest *shared.RespondActivityTaskCanceledRequest) (err error) {
	err = g.h.RespondActivityTaskCanceled(ctx, mapper.ToRespondActivityTaskCanceledRequest(CanceledRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondActivityTaskCanceledByID(ctx context.Context, CanceledRequest *shared.RespondActivityTaskCanceledByIDRequest) (err error) {
	err = g.h.RespondActivityTaskCanceledByID(ctx, mapper.ToRespondActivityTaskCanceledByIDRequest(CanceledRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondActivityTaskCompleted(ctx context.Context, CompleteRequest *shared.RespondActivityTaskCompletedRequest) (err error) {
	err = g.h.RespondActivityTaskCompleted(ctx, mapper.ToRespondActivityTaskCompletedRequest(CompleteRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondActivityTaskCompletedByID(ctx context.Context, CompleteRequest *shared.RespondActivityTaskCompletedByIDRequest) (err error) {
	err = g.h.RespondActivityTaskCompletedByID(ctx, mapper.ToRespondActivityTaskCompletedByIDRequest(CompleteRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondActivityTaskFailed(ctx context.Context, FailRequest *shared.RespondActivityTaskFailedRequest) (err error) {
	err = g.h.RespondActivityTaskFailed(ctx, mapper.ToRespondActivityTaskFailedRequest(FailRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondActivityTaskFailedByID(ctx context.Context, FailRequest *shared.RespondActivityTaskFailedByIDRequest) (err error) {
	err = g.h.RespondActivityTaskFailedByID(ctx, mapper.ToRespondActivityTaskFailedByIDRequest(FailRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondDecisionTaskCompleted(ctx context.Context, CompleteRequest *shared.RespondDecisionTaskCompletedRequest) (rp1 *shared.RespondDecisionTaskCompletedResponse, err error) {
	response, err := g.h.RespondDecisionTaskCompleted(ctx, mapper.ToRespondDecisionTaskCompletedRequest(CompleteRequest))
	return mapper.FromRespondDecisionTaskCompletedResponse(response), mapper.FromError(err)
}

func (g APIHandler) RespondDecisionTaskFailed(ctx context.Context, FailedRequest *shared.RespondDecisionTaskFailedRequest) (err error) {
	err = g.h.RespondDecisionTaskFailed(ctx, mapper.ToRespondDecisionTaskFailedRequest(FailedRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RespondQueryTaskCompleted(ctx context.Context, CompleteRequest *shared.RespondQueryTaskCompletedRequest) (err error) {
	err = g.h.RespondQueryTaskCompleted(ctx, mapper.ToRespondQueryTaskCompletedRequest(CompleteRequest))
	return mapper.FromError(err)
}

func (g APIHandler) RestartWorkflowExecution(ctx context.Context, RestartRequest *shared.RestartWorkflowExecutionRequest) (rp1 *shared.RestartWorkflowExecutionResponse, err error) {
	response, err := g.h.RestartWorkflowExecution(ctx, mapper.ToRestartWorkflowExecutionRequest(RestartRequest))
	return mapper.FromRestartWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g APIHandler) ScanWorkflowExecutions(ctx context.Context, ListRequest *shared.ListWorkflowExecutionsRequest) (lp1 *shared.ListWorkflowExecutionsResponse, err error) {
	response, err := g.h.ScanWorkflowExecutions(ctx, mapper.ToScanWorkflowExecutionsRequest(ListRequest))
	return mapper.FromScanWorkflowExecutionsResponse(response), mapper.FromError(err)
}

func (g APIHandler) SignalWithStartWorkflowExecution(ctx context.Context, SignalWithStartRequest *shared.SignalWithStartWorkflowExecutionRequest) (sp1 *shared.StartWorkflowExecutionResponse, err error) {
	response, err := g.h.SignalWithStartWorkflowExecution(ctx, mapper.ToSignalWithStartWorkflowExecutionRequest(SignalWithStartRequest))
	return mapper.FromSignalWithStartWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g APIHandler) SignalWithStartWorkflowExecutionAsync(ctx context.Context, SignalWithStartRequest *shared.SignalWithStartWorkflowExecutionAsyncRequest) (sp1 *shared.SignalWithStartWorkflowExecutionAsyncResponse, err error) {
	response, err := g.h.SignalWithStartWorkflowExecutionAsync(ctx, mapper.ToSignalWithStartWorkflowExecutionAsyncRequest(SignalWithStartRequest))
	return mapper.FromSignalWithStartWorkflowExecutionAsyncResponse(response), mapper.FromError(err)
}

func (g APIHandler) SignalWorkflowExecution(ctx context.Context, SignalRequest *shared.SignalWorkflowExecutionRequest) (err error) {
	err = g.h.SignalWorkflowExecution(ctx, mapper.ToSignalWorkflowExecutionRequest(SignalRequest))
	return mapper.FromError(err)
}

func (g APIHandler) StartWorkflowExecution(ctx context.Context, StartRequest *shared.StartWorkflowExecutionRequest) (sp1 *shared.StartWorkflowExecutionResponse, err error) {
	response, err := g.h.StartWorkflowExecution(ctx, mapper.ToStartWorkflowExecutionRequest(StartRequest))
	return mapper.FromStartWorkflowExecutionResponse(response), mapper.FromError(err)
}

func (g APIHandler) StartWorkflowExecutionAsync(ctx context.Context, StartRequest *shared.StartWorkflowExecutionAsyncRequest) (sp1 *shared.StartWorkflowExecutionAsyncResponse, err error) {
	response, err := g.h.StartWorkflowExecutionAsync(ctx, mapper.ToStartWorkflowExecutionAsyncRequest(StartRequest))
	return mapper.FromStartWorkflowExecutionAsyncResponse(response), mapper.FromError(err)
}

func (g APIHandler) TerminateWorkflowExecution(ctx context.Context, TerminateRequest *shared.TerminateWorkflowExecutionRequest) (err error) {
	err = g.h.TerminateWorkflowExecution(ctx, mapper.ToTerminateWorkflowExecutionRequest(TerminateRequest))
	return mapper.FromError(err)
}

func (g APIHandler) UnpauseSchedule(ctx context.Context, Request *shared.UnpauseScheduleRequest) (up1 *shared.UnpauseScheduleResponse, err error) {
	response, err := g.h.UnpauseSchedule(ctx, mapper.ToUnpauseScheduleRequest(Request))
	return mapper.FromUnpauseScheduleResponse(response), mapper.FromError(err)
}

func (g APIHandler) UpdateDomain(ctx context.Context, UpdateRequest *shared.UpdateDomainRequest) (up1 *shared.UpdateDomainResponse, err error) {
	response, err := g.h.UpdateDomain(ctx, mapper.ToUpdateDomainRequest(UpdateRequest))
	return mapper.FromUpdateDomainResponse(response), mapper.FromError(err)
}

func (g APIHandler) UpdateSchedule(ctx context.Context, Request *shared.UpdateScheduleRequest) (up1 *shared.UpdateScheduleResponse, err error) {
	response, err := g.h.UpdateSchedule(ctx, mapper.ToUpdateScheduleRequest(Request))
	return mapper.FromUpdateScheduleResponse(response), mapper.FromError(err)
}
