// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedDomainManager implements _sourcePersistence.DomainManager interface instrumented with rate limiter.
type ratelimitedDomainManager struct {
	wrapped      _sourcePersistence.DomainManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewDomainManager creates a new instance of DomainManager with ratelimiter.
func NewDomainManager(
	wrapped persistence.DomainManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.DomainManager {
	return &ratelimitedDomainManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedDomainManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedDomainManager) CreateDomain(ctx context.Context, request *_sourcePersistence.CreateDomainRequest) (cp1 *_sourcePersistence.CreateDomainResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateDomain(ctx, request)
}

func (c *ratelimitedDomainManager) DeleteDomain(ctx context.Context, request *_sourcePersistence.DeleteDomainRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteDomain(ctx, request)
}

func (c *ratelimitedDomainManager) DeleteDomainByName(ctx context.Context, request *_sourcePersistence.DeleteDomainByNameRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteDomainByName(ctx, request)
}

func (c *ratelimitedDomainManager) GetDomain(ctx context.Context, request *_sourcePersistence.GetDomainRequest) (gp1 *_sourcePersistence.GetDomainResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDomain(ctx, request)
}

func (c *ratelimitedDomainManager) GetMetadata(ctx context.Context) (gp1 *_sourcePersistence.GetMetadataResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetMetadata(ctx)
}

func (c *ratelimitedDomainManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedDomainManager) ListDomains(ctx context.Context, request *_sourcePersistence.ListDomainsRequest) (lp1 *_sourcePersistence.ListDomainsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListDomains(ctx, request)
}

func (c *ratelimitedDomainManager) UpdateDomain(ctx context.Context, request *_sourcePersistence.UpdateDomainRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateDomain(ctx, request)
}
