// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
	"github.com/uber/cadence/common/types"
)

// ratelimitedExecutionManager implements _sourcePersistence.ExecutionManager interface instrumented with rate limiter.
type ratelimitedExecutionManager struct {
	wrapped      _sourcePersistence.ExecutionManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewExecutionManager creates a new instance of ExecutionManager with ratelimiter.
func NewExecutionManager(
	wrapped persistence.ExecutionManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.ExecutionManager {
	return &ratelimitedExecutionManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedExecutionManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedExecutionManager) CompleteHistoryTask(ctx context.Context, request *_sourcePersistence.CompleteHistoryTaskRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CompleteHistoryTask(ctx, request)
}

func (c *ratelimitedExecutionManager) ConflictResolveWorkflowExecution(ctx context.Context, request *_sourcePersistence.ConflictResolveWorkflowExecutionRequest) (cp1 *_sourcePersistence.ConflictResolveWorkflowExecutionResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ConflictResolveWorkflowExecution(ctx, request)
}

func (c *ratelimitedExecutionManager) CreateFailoverMarkerTasks(ctx context.Context, request *_sourcePersistence.CreateFailoverMarkersRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateFailoverMarkerTasks(ctx, request)
}

func (c *ratelimitedExecutionManager) CreateWorkflowExecution(ctx context.Context, request *_sourcePersistence.CreateWorkflowExecutionRequest) (cp1 *_sourcePersistence.CreateWorkflowExecutionResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateWorkflowExecution(ctx, request)
}

func (c *ratelimitedExecutionManager) DeleteActiveClusterSelectionPolicy(ctx context.Context, request *_sourcePersistence.DeleteActiveClusterSelectionPolicyRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteActiveClusterSelectionPolicy(ctx, request)
}

func (c *ratelimitedExecutionManager) DeleteCurrentWorkflowExecution(ctx context.Context, request *_sourcePersistence.DeleteCurrentWorkflowExecutionRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteCurrentWorkflowExecution(ctx, request)
}

func (c *ratelimitedExecutionManager) DeleteReplicationTaskFromDLQ(ctx context.Context, request *_sourcePersistence.DeleteReplicationTaskFromDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteReplicationTaskFromDLQ(ctx, request)
}

func (c *ratelimitedExecutionManager) DeleteWorkflowExecution(ctx context.Context, request *_sourcePersistence.DeleteWorkflowExecutionRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteWorkflowExecution(ctx, request)
}

func (c *ratelimitedExecutionManager) FetchWorkflowTimerTasksForCleanup(ctx context.Context, request *_sourcePersistence.FetchWorkflowTimerTasksForCleanupRequest) (ha1 []_sourcePersistence.HistoryTaskKey, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.FetchWorkflowTimerTasksForCleanup(ctx, request)
}

func (c *ratelimitedExecutionManager) GetActiveClusterSelectionPolicy(ctx context.Context, request *_sourcePersistence.GetActiveClusterSelectionPolicyRequest) (ap1 *types.ActiveClusterSelectionPolicy, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetActiveClusterSelectionPolicy(ctx, request)
}

func (c *ratelimitedExecutionManager) GetCurrentExecution(ctx context.Context, request *_sourcePersistence.GetCurrentExecutionRequest) (gp1 *_sourcePersistence.GetCurrentExecutionResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetCurrentExecution(ctx, request)
}

func (c *ratelimitedExecutionManager) GetHistoryTasks(ctx context.Context, request *_sourcePersistence.GetHistoryTasksRequest) (gp1 *_sourcePersistence.GetHistoryTasksResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetHistoryTasks(ctx, request)
}

func (c *ratelimitedExecutionManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedExecutionManager) GetReplicationDLQSize(ctx context.Context, request *_sourcePersistence.GetReplicationDLQSizeRequest) (gp1 *_sourcePersistence.GetReplicationDLQSizeResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetReplicationDLQSize(ctx, request)
}

func (c *ratelimitedExecutionManager) GetReplicationTasksFromDLQ(ctx context.Context, request *_sourcePersistence.GetReplicationTasksFromDLQRequest) (gp1 *_sourcePersistence.GetReplicationDLQTasksResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetReplicationTasksFromDLQ(ctx, request)
}

func (c *ratelimitedExecutionManager) GetShardID() (i1 int) {
	return c.wrapped.GetShardID()
}

func (c *ratelimitedExecutionManager) GetWorkflowExecution(ctx context.Context, request *_sourcePersistence.GetWorkflowExecutionRequest) (gp1 *_sourcePersistence.GetWorkflowExecutionResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetWorkflowExecution(ctx, request)
}

func (c *ratelimitedExecutionManager) IsWorkflowExecutionExists(ctx context.Context, request *_sourcePersistence.IsWorkflowExecutionExistsRequest) (ip1 *_sourcePersistence.IsWorkflowExecutionExistsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.IsWorkflowExecutionExists(ctx, request)
}

func (c *ratelimitedExecutionManager) ListConcreteExecutions(ctx context.Context, request *_sourcePersistence.ListConcreteExecutionsRequest) (lp1 *_sourcePersistence.ListConcreteExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListConcreteExecutions(ctx, request)
}

func (c *ratelimitedExecutionManager) ListCurrentExecutions(ctx context.Context, request *_sourcePersistence.ListCurrentExecutionsRequest) (lp1 *_sourcePersistence.ListCurrentExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListCurrentExecutions(ctx, request)
}

func (c *ratelimitedExecutionManager) PutReplicationTaskToDLQ(ctx context.Context, request *_sourcePersistence.PutReplicationTaskToDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.PutReplicationTaskToDLQ(ctx, request)
}

func (c *ratelimitedExecutionManager) RangeCompleteHistoryTask(ctx context.Context, request *_sourcePersistence.RangeCompleteHistoryTaskRequest) (rp1 *_sourcePersistence.RangeCompleteHistoryTaskResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeCompleteHistoryTask(ctx, request)
}

func (c *ratelimitedExecutionManager) RangeDeleteReplicationTaskFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteReplicationTaskFromDLQRequest) (rp1 *_sourcePersistence.RangeDeleteReplicationTaskFromDLQResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteReplicationTaskFromDLQ(ctx, request)
}

func (c *ratelimitedExecutionManager) UpdateWorkflowExecution(ctx context.Context, request *_sourcePersistence.UpdateWorkflowExecutionRequest) (up1 *_sourcePersistence.UpdateWorkflowExecutionResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateWorkflowExecution(ctx, request)
}
