// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedHistoryTaskDLQManager implements _sourcePersistence.HistoryTaskDLQManager interface instrumented with rate limiter.
type ratelimitedHistoryTaskDLQManager struct {
	wrapped      _sourcePersistence.HistoryTaskDLQManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewHistoryTaskDLQManager creates a new instance of HistoryTaskDLQManager with ratelimiter.
func NewHistoryTaskDLQManager(
	wrapped persistence.HistoryTaskDLQManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.HistoryTaskDLQManager {
	return &ratelimitedHistoryTaskDLQManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedHistoryTaskDLQManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedHistoryTaskDLQManager) CreateHistoryDLQAckLevelIfNotExists(ctx context.Context, request _sourcePersistence.CreateHistoryDLQAckLevelRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateHistoryDLQAckLevelIfNotExists(ctx, request)
}

func (c *ratelimitedHistoryTaskDLQManager) CreateHistoryDLQTask(ctx context.Context, request _sourcePersistence.CreateHistoryDLQTaskRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateHistoryDLQTask(ctx, request)
}

func (c *ratelimitedHistoryTaskDLQManager) DeleteHistoryDLQTasks(ctx context.Context, request _sourcePersistence.HistoryDLQDeleteTasksRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteHistoryDLQTasks(ctx, request)
}

func (c *ratelimitedHistoryTaskDLQManager) GetHistoryDLQAckLevels(ctx context.Context, request _sourcePersistence.HistoryDLQGetAckLevelsRequest) (ha1 []_sourcePersistence.HistoryDLQAckLevel, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetHistoryDLQAckLevels(ctx, request)
}

func (c *ratelimitedHistoryTaskDLQManager) GetHistoryDLQTasks(ctx context.Context, request _sourcePersistence.HistoryDLQGetTasksRequest) (h1 _sourcePersistence.HistoryDLQGetTasksResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetHistoryDLQTasks(ctx, request)
}

func (c *ratelimitedHistoryTaskDLQManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedHistoryTaskDLQManager) UpdateHistoryDLQAckLevel(ctx context.Context, request _sourcePersistence.HistoryDLQUpdateAckLevelRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateHistoryDLQAckLevel(ctx, request)
}
