// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedHistoryManager implements _sourcePersistence.HistoryManager interface instrumented with rate limiter.
type ratelimitedHistoryManager struct {
	wrapped      _sourcePersistence.HistoryManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewHistoryManager creates a new instance of HistoryManager with ratelimiter.
func NewHistoryManager(
	wrapped persistence.HistoryManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.HistoryManager {
	return &ratelimitedHistoryManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedHistoryManager) AppendHistoryNodes(ctx context.Context, request *_sourcePersistence.AppendHistoryNodesRequest) (ap1 *_sourcePersistence.AppendHistoryNodesResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.AppendHistoryNodes(ctx, request)
}

func (c *ratelimitedHistoryManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedHistoryManager) DeleteHistoryBranch(ctx context.Context, request *_sourcePersistence.DeleteHistoryBranchRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteHistoryBranch(ctx, request)
}

func (c *ratelimitedHistoryManager) ForkHistoryBranch(ctx context.Context, request *_sourcePersistence.ForkHistoryBranchRequest) (fp1 *_sourcePersistence.ForkHistoryBranchResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ForkHistoryBranch(ctx, request)
}

func (c *ratelimitedHistoryManager) GetAllHistoryTreeBranches(ctx context.Context, request *_sourcePersistence.GetAllHistoryTreeBranchesRequest) (gp1 *_sourcePersistence.GetAllHistoryTreeBranchesResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetAllHistoryTreeBranches(ctx, request)
}

func (c *ratelimitedHistoryManager) GetHistoryTree(ctx context.Context, request *_sourcePersistence.GetHistoryTreeRequest) (gp1 *_sourcePersistence.GetHistoryTreeResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetHistoryTree(ctx, request)
}

func (c *ratelimitedHistoryManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedHistoryManager) ReadHistoryBranch(ctx context.Context, request *_sourcePersistence.ReadHistoryBranchRequest) (rp1 *_sourcePersistence.ReadHistoryBranchResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadHistoryBranch(ctx, request)
}

func (c *ratelimitedHistoryManager) ReadHistoryBranchByBatch(ctx context.Context, request *_sourcePersistence.ReadHistoryBranchRequest) (rp1 *_sourcePersistence.ReadHistoryBranchByBatchResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadHistoryBranchByBatch(ctx, request)
}

func (c *ratelimitedHistoryManager) ReadRawHistoryBranch(ctx context.Context, request *_sourcePersistence.ReadHistoryBranchRequest) (rp1 *_sourcePersistence.ReadRawHistoryBranchResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadRawHistoryBranch(ctx, request)
}
