// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedQueueManager implements _sourcePersistence.QueueManager interface instrumented with rate limiter.
type ratelimitedQueueManager struct {
	wrapped      _sourcePersistence.QueueManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewQueueManager creates a new instance of QueueManager with ratelimiter.
func NewQueueManager(
	wrapped persistence.QueueManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.QueueManager {
	return &ratelimitedQueueManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedQueueManager) DeleteMessageFromDLQ(ctx context.Context, request *_sourcePersistence.DeleteMessageFromDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteMessageFromDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) DeleteMessagesBefore(ctx context.Context, request *_sourcePersistence.DeleteMessagesBeforeRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteMessagesBefore(ctx, request)
}

func (c *ratelimitedQueueManager) EnqueueMessage(ctx context.Context, request *_sourcePersistence.EnqueueMessageRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueMessage(ctx, request)
}

func (c *ratelimitedQueueManager) EnqueueMessageToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueMessageToDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueMessageToDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) GetAckLevels(ctx context.Context, request *_sourcePersistence.GetAckLevelsRequest) (gp1 *_sourcePersistence.GetAckLevelsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetAckLevels(ctx, request)
}

func (c *ratelimitedQueueManager) GetDLQAckLevels(ctx context.Context, request *_sourcePersistence.GetDLQAckLevelsRequest) (gp1 *_sourcePersistence.GetDLQAckLevelsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDLQAckLevels(ctx, request)
}

func (c *ratelimitedQueueManager) GetDLQSize(ctx context.Context, request *_sourcePersistence.GetDLQSizeRequest) (gp1 *_sourcePersistence.GetDLQSizeResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDLQSize(ctx, request)
}

func (c *ratelimitedQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteMessagesFromDLQRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) ReadMessages(ctx context.Context, request *_sourcePersistence.ReadMessagesRequest) (rp1 *_sourcePersistence.ReadMessagesResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadMessages(ctx, request)
}

func (c *ratelimitedQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadMessagesFromDLQRequest) (rp1 *_sourcePersistence.ReadMessagesFromDLQResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) UpdateAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAckLevelRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateAckLevel(ctx, request)
}

func (c *ratelimitedQueueManager) UpdateDLQAckLevel(ctx context.Context, request *_sourcePersistence.UpdateDLQAckLevelRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateDLQAckLevel(ctx, request)
}
