// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedShardManager implements _sourcePersistence.ShardManager interface instrumented with rate limiter.
type ratelimitedShardManager struct {
	wrapped      _sourcePersistence.ShardManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewShardManager creates a new instance of ShardManager with ratelimiter.
func NewShardManager(
	wrapped persistence.ShardManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.ShardManager {
	return &ratelimitedShardManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedShardManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedShardManager) CreateShard(ctx context.Context, request *_sourcePersistence.CreateShardRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateShard(ctx, request)
}

func (c *ratelimitedShardManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedShardManager) GetShard(ctx context.Context, request *_sourcePersistence.GetShardRequest) (gp1 *_sourcePersistence.GetShardResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetShard(ctx, request)
}

func (c *ratelimitedShardManager) UpdateShard(ctx context.Context, request *_sourcePersistence.UpdateShardRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateShard(ctx, request)
}
