// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedTaskManager implements _sourcePersistence.TaskManager interface instrumented with rate limiter.
type ratelimitedTaskManager struct {
	wrapped      _sourcePersistence.TaskManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewTaskManager creates a new instance of TaskManager with ratelimiter.
func NewTaskManager(
	wrapped persistence.TaskManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.TaskManager {
	return &ratelimitedTaskManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedTaskManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedTaskManager) CompleteTask(ctx context.Context, request *_sourcePersistence.CompleteTaskRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CompleteTask(ctx, request)
}

func (c *ratelimitedTaskManager) CompleteTasksLessThan(ctx context.Context, request *_sourcePersistence.CompleteTasksLessThanRequest) (cp1 *_sourcePersistence.CompleteTasksLessThanResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CompleteTasksLessThan(ctx, request)
}

func (c *ratelimitedTaskManager) CreateTasks(ctx context.Context, request *_sourcePersistence.CreateTasksRequest) (cp1 *_sourcePersistence.CreateTasksResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateTasks(ctx, request)
}

func (c *ratelimitedTaskManager) DeleteTaskList(ctx context.Context, request *_sourcePersistence.DeleteTaskListRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedTaskManager) GetOrphanTasks(ctx context.Context, request *_sourcePersistence.GetOrphanTasksRequest) (gp1 *_sourcePersistence.GetOrphanTasksResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetOrphanTasks(ctx, request)
}

func (c *ratelimitedTaskManager) GetTaskList(ctx context.Context, request *_sourcePersistence.GetTaskListRequest) (gp1 *_sourcePersistence.GetTaskListResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) GetTaskListSize(ctx context.Context, request *_sourcePersistence.GetTaskListSizeRequest) (gp1 *_sourcePersistence.GetTaskListSizeResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetTaskListSize(ctx, request)
}

func (c *ratelimitedTaskManager) GetTasks(ctx context.Context, request *_sourcePersistence.GetTasksRequest) (gp1 *_sourcePersistence.GetTasksResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetTasks(ctx, request)
}

func (c *ratelimitedTaskManager) LeaseTaskList(ctx context.Context, request *_sourcePersistence.LeaseTaskListRequest) (lp1 *_sourcePersistence.LeaseTaskListResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.LeaseTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) ListTaskList(ctx context.Context, request *_sourcePersistence.ListTaskListRequest) (lp1 *_sourcePersistence.ListTaskListResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) UpdateTaskList(ctx context.Context, request *_sourcePersistence.UpdateTaskListRequest) (up1 *_sourcePersistence.UpdateTaskListResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateTaskList(ctx, request)
}
