// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package ratelimited

import (
	"context"

	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedVisibilityManager implements _sourcePersistence.VisibilityManager interface instrumented with rate limiter.
type ratelimitedVisibilityManager struct {
	wrapped      _sourcePersistence.VisibilityManager
	rateLimiter  quotas.Limiter
	callerBypass quotas.CallerBypass
}

// NewVisibilityManager creates a new instance of VisibilityManager with ratelimiter.
func NewVisibilityManager(
	wrapped persistence.VisibilityManager,
	rateLimiter quotas.Limiter,
	callerBypass quotas.CallerBypass,
) persistence.VisibilityManager {
	return &ratelimitedVisibilityManager{
		wrapped:      wrapped,
		rateLimiter:  rateLimiter,
		callerBypass: callerBypass,
	}
}

func (c *ratelimitedVisibilityManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedVisibilityManager) CountWorkflowExecutions(ctx context.Context, request *_sourcePersistence.CountWorkflowExecutionsRequest) (cp1 *_sourcePersistence.CountWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CountWorkflowExecutions(ctx, request)
}

func (c *ratelimitedVisibilityManager) DeleteUninitializedWorkflowExecution(ctx context.Context, request *_sourcePersistence.VisibilityDeleteWorkflowExecutionRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteUninitializedWorkflowExecution(ctx, request)
}

func (c *ratelimitedVisibilityManager) DeleteWorkflowExecution(ctx context.Context, request *_sourcePersistence.VisibilityDeleteWorkflowExecutionRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteWorkflowExecution(ctx, request)
}

func (c *ratelimitedVisibilityManager) GetClosedWorkflowExecution(ctx context.Context, request *_sourcePersistence.GetClosedWorkflowExecutionRequest) (gp1 *_sourcePersistence.GetClosedWorkflowExecutionResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetClosedWorkflowExecution(ctx, request)
}

func (c *ratelimitedVisibilityManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedVisibilityManager) ListClosedWorkflowExecutions(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListClosedWorkflowExecutions(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListClosedWorkflowExecutionsByStatus(ctx context.Context, request *_sourcePersistence.ListClosedWorkflowExecutionsByStatusRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListClosedWorkflowExecutionsByStatus(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListClosedWorkflowExecutionsByType(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsByTypeRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListClosedWorkflowExecutionsByType(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListClosedWorkflowExecutionsByWorkflowID(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsByWorkflowIDRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListClosedWorkflowExecutionsByWorkflowID(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListOpenWorkflowExecutions(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListOpenWorkflowExecutions(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListOpenWorkflowExecutionsByType(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsByTypeRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListOpenWorkflowExecutionsByType(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListOpenWorkflowExecutionsByWorkflowID(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsByWorkflowIDRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListOpenWorkflowExecutionsByWorkflowID(ctx, request)
}

func (c *ratelimitedVisibilityManager) ListWorkflowExecutions(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsByQueryRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListWorkflowExecutions(ctx, request)
}

func (c *ratelimitedVisibilityManager) RecordWorkflowExecutionClosed(ctx context.Context, request *_sourcePersistence.RecordWorkflowExecutionClosedRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RecordWorkflowExecutionClosed(ctx, request)
}

func (c *ratelimitedVisibilityManager) RecordWorkflowExecutionStarted(ctx context.Context, request *_sourcePersistence.RecordWorkflowExecutionStartedRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RecordWorkflowExecutionStarted(ctx, request)
}

func (c *ratelimitedVisibilityManager) RecordWorkflowExecutionUninitialized(ctx context.Context, request *_sourcePersistence.RecordWorkflowExecutionUninitializedRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RecordWorkflowExecutionUninitialized(ctx, request)
}

func (c *ratelimitedVisibilityManager) ScanWorkflowExecutions(ctx context.Context, request *_sourcePersistence.ListWorkflowExecutionsByQueryRequest) (lp1 *_sourcePersistence.ListWorkflowExecutionsResponse, err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ScanWorkflowExecutions(ctx, request)
}

func (c *ratelimitedVisibilityManager) UpsertWorkflowExecution(ctx context.Context, request *_sourcePersistence.UpsertWorkflowExecutionRequest) (err error) {
	if !c.callerBypass.AllowLimiter(ctx, c.rateLimiter) {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpsertWorkflowExecution(ctx, request)
}
