// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered_execution.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metered

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/dynamicconfig/dynamicproperties"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/log/tag"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/types"
)

// meteredExecutionManager implements _sourcePersistence.ExecutionManager interface instrumented with rate limiter.
type meteredExecutionManager struct {
	base
	wrapped _sourcePersistence.ExecutionManager
}

// NewExecutionManager creates a new instance of ExecutionManager with ratelimiter.
func NewExecutionManager(
	wrapped persistence.ExecutionManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
	enableShardIDMetrics dynamicproperties.BoolPropertyFn,
) persistence.ExecutionManager {
	return &meteredExecutionManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			enableShardIDMetrics:          enableShardIDMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredExecutionManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredExecutionManager) CompleteHistoryTask(ctx context.Context, request *_sourcePersistence.CompleteHistoryTaskRequest) (err error) {
	op := func() error {
		err = c.wrapped.CompleteHistoryTask(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence CompleteHistoryTask called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceCompleteHistoryTaskScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceCompleteHistoryTaskScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceCompleteHistoryTaskScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceCompleteHistoryTaskScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) ConflictResolveWorkflowExecution(ctx context.Context, request *_sourcePersistence.ConflictResolveWorkflowExecutionRequest) (cp1 *_sourcePersistence.ConflictResolveWorkflowExecutionResponse, err error) {
	op := func() error {
		cp1, err = c.wrapped.ConflictResolveWorkflowExecution(ctx, request)
		c.emptyMetric("ExecutionManager.ConflictResolveWorkflowExecution", request, cp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence ConflictResolveWorkflowExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceConflictResolveWorkflowExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceConflictResolveWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceConflictResolveWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceConflictResolveWorkflowExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) CreateFailoverMarkerTasks(ctx context.Context, request *_sourcePersistence.CreateFailoverMarkersRequest) (err error) {
	op := func() error {
		err = c.wrapped.CreateFailoverMarkerTasks(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence CreateFailoverMarkerTasks called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceCreateFailoverMarkerTasksScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceCreateFailoverMarkerTasksScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceCreateFailoverMarkerTasksScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceCreateFailoverMarkerTasksScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) CreateHistoryTasks(ctx context.Context, request *_sourcePersistence.CreateHistoryTasksRequest) (err error) {
	op := func() error {
		err = c.wrapped.CreateHistoryTasks(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence CreateHistoryTasks called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceCreateHistoryTasksScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceCreateHistoryTasksScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceCreateHistoryTasksScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceCreateHistoryTasksScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) CreateWorkflowExecution(ctx context.Context, request *_sourcePersistence.CreateWorkflowExecutionRequest) (cp1 *_sourcePersistence.CreateWorkflowExecutionResponse, err error) {
	op := func() error {
		cp1, err = c.wrapped.CreateWorkflowExecution(ctx, request)
		c.emptyMetric("ExecutionManager.CreateWorkflowExecution", request, cp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence CreateWorkflowExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceCreateWorkflowExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceCreateWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceCreateWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceCreateWorkflowExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) DeleteActiveClusterSelectionPolicy(ctx context.Context, request *_sourcePersistence.DeleteActiveClusterSelectionPolicyRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteActiveClusterSelectionPolicy(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence DeleteActiveClusterSelectionPolicy called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceDeleteActiveClusterSelectionPolicyScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceDeleteActiveClusterSelectionPolicyScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceDeleteActiveClusterSelectionPolicyScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceDeleteActiveClusterSelectionPolicyScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) DeleteCurrentWorkflowExecution(ctx context.Context, request *_sourcePersistence.DeleteCurrentWorkflowExecutionRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteCurrentWorkflowExecution(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence DeleteCurrentWorkflowExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceDeleteCurrentWorkflowExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceDeleteCurrentWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceDeleteCurrentWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceDeleteCurrentWorkflowExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) DeleteReplicationTaskFromDLQ(ctx context.Context, request *_sourcePersistence.DeleteReplicationTaskFromDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteReplicationTaskFromDLQ(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence DeleteReplicationTaskFromDLQ called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceDeleteReplicationTaskFromDLQScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceDeleteReplicationTaskFromDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceDeleteReplicationTaskFromDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceDeleteReplicationTaskFromDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) DeleteWorkflowExecution(ctx context.Context, request *_sourcePersistence.DeleteWorkflowExecutionRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteWorkflowExecution(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence DeleteWorkflowExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceDeleteWorkflowExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceDeleteWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceDeleteWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceDeleteWorkflowExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) FetchWorkflowTimerTasksForCleanup(ctx context.Context, request *_sourcePersistence.FetchWorkflowTimerTasksForCleanupRequest) (ha1 []_sourcePersistence.HistoryTaskKey, err error) {
	op := func() error {
		ha1, err = c.wrapped.FetchWorkflowTimerTasksForCleanup(ctx, request)
		c.emptyMetric("ExecutionManager.FetchWorkflowTimerTasksForCleanup", request, ha1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence FetchWorkflowTimerTasksForCleanup called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceFetchWorkflowTimerTasksForCleanupScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceFetchWorkflowTimerTasksForCleanupScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceFetchWorkflowTimerTasksForCleanupScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceFetchWorkflowTimerTasksForCleanupScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) GetActiveClusterSelectionPolicy(ctx context.Context, request *_sourcePersistence.GetActiveClusterSelectionPolicyRequest) (ap1 *types.ActiveClusterSelectionPolicy, err error) {
	op := func() error {
		ap1, err = c.wrapped.GetActiveClusterSelectionPolicy(ctx, request)
		c.emptyMetric("ExecutionManager.GetActiveClusterSelectionPolicy", request, ap1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence GetActiveClusterSelectionPolicy called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceGetActiveClusterSelectionPolicyScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceGetActiveClusterSelectionPolicyScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceGetActiveClusterSelectionPolicyScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceGetActiveClusterSelectionPolicyScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) GetCurrentExecution(ctx context.Context, request *_sourcePersistence.GetCurrentExecutionRequest) (gp1 *_sourcePersistence.GetCurrentExecutionResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetCurrentExecution(ctx, request)
		c.emptyMetric("ExecutionManager.GetCurrentExecution", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence GetCurrentExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceGetCurrentExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceGetCurrentExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceGetCurrentExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceGetCurrentExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) GetHistoryTasks(ctx context.Context, request *_sourcePersistence.GetHistoryTasksRequest) (gp1 *_sourcePersistence.GetHistoryTasksResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetHistoryTasks(ctx, request)
		c.emptyMetric("ExecutionManager.GetHistoryTasks", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence GetHistoryTasks called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceGetHistoryTasksScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceGetHistoryTasksScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceGetHistoryTasksScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceGetHistoryTasksScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *meteredExecutionManager) GetReplicationDLQSize(ctx context.Context, request *_sourcePersistence.GetReplicationDLQSizeRequest) (gp1 *_sourcePersistence.GetReplicationDLQSizeResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetReplicationDLQSize(ctx, request)
		c.emptyMetric("ExecutionManager.GetReplicationDLQSize", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence GetReplicationDLQSize called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceGetReplicationDLQSizeScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceGetReplicationDLQSizeScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceGetReplicationDLQSizeScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceGetReplicationDLQSizeScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) GetReplicationTasksFromDLQ(ctx context.Context, request *_sourcePersistence.GetReplicationTasksFromDLQRequest) (gp1 *_sourcePersistence.GetReplicationDLQTasksResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetReplicationTasksFromDLQ(ctx, request)
		c.emptyMetric("ExecutionManager.GetReplicationTasksFromDLQ", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence GetReplicationTasksFromDLQ called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceGetReplicationTasksFromDLQScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceGetReplicationTasksFromDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceGetReplicationTasksFromDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceGetReplicationTasksFromDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) GetWorkflowExecution(ctx context.Context, request *_sourcePersistence.GetWorkflowExecutionRequest) (gp1 *_sourcePersistence.GetWorkflowExecutionResponse, err error) {
	op := func() error {
		gp1, err = c.wrapped.GetWorkflowExecution(ctx, request)
		c.emptyMetric("ExecutionManager.GetWorkflowExecution", request, gp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence GetWorkflowExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceGetWorkflowExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceGetWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceGetWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceGetWorkflowExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) IsWorkflowExecutionExists(ctx context.Context, request *_sourcePersistence.IsWorkflowExecutionExistsRequest) (ip1 *_sourcePersistence.IsWorkflowExecutionExistsResponse, err error) {
	op := func() error {
		ip1, err = c.wrapped.IsWorkflowExecutionExists(ctx, request)
		c.emptyMetric("ExecutionManager.IsWorkflowExecutionExists", request, ip1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence IsWorkflowExecutionExists called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceIsWorkflowExecutionExistsScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceIsWorkflowExecutionExistsScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceIsWorkflowExecutionExistsScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceIsWorkflowExecutionExistsScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) ListConcreteExecutions(ctx context.Context, request *_sourcePersistence.ListConcreteExecutionsRequest) (lp1 *_sourcePersistence.ListConcreteExecutionsResponse, err error) {
	op := func() error {
		lp1, err = c.wrapped.ListConcreteExecutions(ctx, request)
		c.emptyMetric("ExecutionManager.ListConcreteExecutions", request, lp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence ListConcreteExecutions called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceListConcreteExecutionsScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceListConcreteExecutionsScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceListConcreteExecutionsScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceListConcreteExecutionsScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) ListCurrentExecutions(ctx context.Context, request *_sourcePersistence.ListCurrentExecutionsRequest) (lp1 *_sourcePersistence.ListCurrentExecutionsResponse, err error) {
	op := func() error {
		lp1, err = c.wrapped.ListCurrentExecutions(ctx, request)
		c.emptyMetric("ExecutionManager.ListCurrentExecutions", request, lp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence ListCurrentExecutions called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceListCurrentExecutionsScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceListCurrentExecutionsScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceListCurrentExecutionsScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceListCurrentExecutionsScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) PutReplicationTaskToDLQ(ctx context.Context, request *_sourcePersistence.PutReplicationTaskToDLQRequest) (err error) {
	op := func() error {
		err = c.wrapped.PutReplicationTaskToDLQ(ctx, request)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence PutReplicationTaskToDLQ called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistencePutReplicationTaskToDLQScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistencePutReplicationTaskToDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistencePutReplicationTaskToDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistencePutReplicationTaskToDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) RangeCompleteHistoryTask(ctx context.Context, request *_sourcePersistence.RangeCompleteHistoryTaskRequest) (rp1 *_sourcePersistence.RangeCompleteHistoryTaskResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.RangeCompleteHistoryTask(ctx, request)
		c.emptyMetric("ExecutionManager.RangeCompleteHistoryTask", request, rp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence RangeCompleteHistoryTask called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceRangeCompleteHistoryTaskScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceRangeCompleteHistoryTaskScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceRangeCompleteHistoryTaskScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceRangeCompleteHistoryTaskScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) RangeDeleteReplicationTaskFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteReplicationTaskFromDLQRequest) (rp1 *_sourcePersistence.RangeDeleteReplicationTaskFromDLQResponse, err error) {
	op := func() error {
		rp1, err = c.wrapped.RangeDeleteReplicationTaskFromDLQ(ctx, request)
		c.emptyMetric("ExecutionManager.RangeDeleteReplicationTaskFromDLQ", request, rp1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence RangeDeleteReplicationTaskFromDLQ called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceRangeDeleteReplicationTaskFromDLQScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceRangeDeleteReplicationTaskFromDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceRangeDeleteReplicationTaskFromDLQScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceRangeDeleteReplicationTaskFromDLQScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}

func (c *meteredExecutionManager) UpdateWorkflowExecution(ctx context.Context, request *_sourcePersistence.UpdateWorkflowExecutionRequest) (up1 *_sourcePersistence.UpdateWorkflowExecutionResponse, err error) {
	op := func() error {
		up1, err = c.wrapped.UpdateWorkflowExecution(ctx, request)
		c.emptyMetric("ExecutionManager.UpdateWorkflowExecution", request, up1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)
	if domainName, hasDomainName := getDomainNameFromRequest(request); hasDomainName {
		logTags := append([]tag.Tag{tag.WorkflowDomainName(domainName)}, getCustomLogTags(request)...)
		if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
			logTags = append(logTags, tag.ShardID(*shardID))
		}
		c.logger.Debug("Persistence UpdateWorkflowExecution called", logTags...)
		if c.enableShardIDMetrics() {
			if shardID, hasShardID := getShardIDFromRequest(request); hasShardID && shardID != nil {
				err = c.callWithDomainAndShardScope(metrics.PersistenceUpdateWorkflowExecutionScope, op, metrics.DomainTag(domainName),
					metrics.ShardIDTag(*shardID), metrics.IsRetryTag(retryCount > 0))
			} else {
				err = c.call(metrics.PersistenceUpdateWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
			}
		} else {
			err = c.call(metrics.PersistenceUpdateWorkflowExecutionScope, op, metrics.DomainTag(domainName), metrics.IsRetryTag(retryCount > 0))
		}
		return
	}

	err = c.callWithoutDomainTag(metrics.PersistenceUpdateWorkflowExecutionScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)

	return
}
