// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/persistence (interfaces: AdminDB,SetupDB,SchemaDB,Schema)
//
// Generated by this command:
//
//	mockgen -package persistence -destination admin_mock.go -self_package github.com/uber/cadence/common/persistence github.com/uber/cadence/common/persistence AdminDB,SetupDB,SchemaDB,Schema
//

// Package persistence is a generated GoMock package.
package persistence

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminDB is a mock of AdminDB interface.
type MockAdminDB struct {
	ctrl     *gomock.Controller
	recorder *MockAdminDBMockRecorder
	isgomock struct{}
}

// MockAdminDBMockRecorder is the mock recorder for MockAdminDB.
type MockAdminDBMockRecorder struct {
	mock *MockAdminDB
}

// NewMockAdminDB creates a new mock instance.
func NewMockAdminDB(ctrl *gomock.Controller) *MockAdminDB {
	mock := &MockAdminDB{ctrl: ctrl}
	mock.recorder = &MockAdminDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminDB) EXPECT() *MockAdminDBMockRecorder {
	return m.recorder
}

// CreateSchemaDB mocks base method.
func (m *MockAdminDB) CreateSchemaDB() (SchemaDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchemaDB")
	ret0, _ := ret[0].(SchemaDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchemaDB indicates an expected call of CreateSchemaDB.
func (mr *MockAdminDBMockRecorder) CreateSchemaDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchemaDB", reflect.TypeOf((*MockAdminDB)(nil).CreateSchemaDB))
}

// CreateSetupDB mocks base method.
func (m *MockAdminDB) CreateSetupDB() (SetupDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetupDB")
	ret0, _ := ret[0].(SetupDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSetupDB indicates an expected call of CreateSetupDB.
func (mr *MockAdminDBMockRecorder) CreateSetupDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetupDB", reflect.TypeOf((*MockAdminDB)(nil).CreateSetupDB))
}

// DBType mocks base method.
func (m *MockAdminDB) DBType() DBType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBType")
	ret0, _ := ret[0].(DBType)
	return ret0
}

// DBType indicates an expected call of DBType.
func (mr *MockAdminDBMockRecorder) DBType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBType", reflect.TypeOf((*MockAdminDB)(nil).DBType))
}

// Identifier mocks base method.
func (m *MockAdminDB) Identifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// Identifier indicates an expected call of Identifier.
func (mr *MockAdminDBMockRecorder) Identifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identifier", reflect.TypeOf((*MockAdminDB)(nil).Identifier))
}

// PluginName mocks base method.
func (m *MockAdminDB) PluginName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PluginName")
	ret0, _ := ret[0].(string)
	return ret0
}

// PluginName indicates an expected call of PluginName.
func (mr *MockAdminDBMockRecorder) PluginName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PluginName", reflect.TypeOf((*MockAdminDB)(nil).PluginName))
}

// SupportsSchema mocks base method.
func (m *MockAdminDB) SupportsSchema() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsSchema")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsSchema indicates an expected call of SupportsSchema.
func (mr *MockAdminDBMockRecorder) SupportsSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsSchema", reflect.TypeOf((*MockAdminDB)(nil).SupportsSchema))
}

// MockSetupDB is a mock of SetupDB interface.
type MockSetupDB struct {
	ctrl     *gomock.Controller
	recorder *MockSetupDBMockRecorder
	isgomock struct{}
}

// MockSetupDBMockRecorder is the mock recorder for MockSetupDB.
type MockSetupDBMockRecorder struct {
	mock *MockSetupDB
}

// NewMockSetupDB creates a new mock instance.
func NewMockSetupDB(ctrl *gomock.Controller) *MockSetupDB {
	mock := &MockSetupDB{ctrl: ctrl}
	mock.recorder = &MockSetupDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetupDB) EXPECT() *MockSetupDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSetupDB) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSetupDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSetupDB)(nil).Close))
}

// IsSetup mocks base method.
func (m *MockSetupDB) IsSetup(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSetup", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSetup indicates an expected call of IsSetup.
func (mr *MockSetupDBMockRecorder) IsSetup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSetup", reflect.TypeOf((*MockSetupDB)(nil).IsSetup), ctx)
}

// Setup mocks base method.
func (m *MockSetupDB) Setup(ctx context.Context, options map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setup", ctx, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup.
func (mr *MockSetupDBMockRecorder) Setup(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockSetupDB)(nil).Setup), ctx, options)
}

// Teardown mocks base method.
func (m *MockSetupDB) Teardown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Teardown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Teardown indicates an expected call of Teardown.
func (mr *MockSetupDBMockRecorder) Teardown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teardown", reflect.TypeOf((*MockSetupDB)(nil).Teardown), ctx)
}

// MockSchemaDB is a mock of SchemaDB interface.
type MockSchemaDB struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaDBMockRecorder
	isgomock struct{}
}

// MockSchemaDBMockRecorder is the mock recorder for MockSchemaDB.
type MockSchemaDBMockRecorder struct {
	mock *MockSchemaDB
}

// NewMockSchemaDB creates a new mock instance.
func NewMockSchemaDB(ctrl *gomock.Controller) *MockSchemaDB {
	mock := &MockSchemaDB{ctrl: ctrl}
	mock.recorder = &MockSchemaDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaDB) EXPECT() *MockSchemaDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSchemaDB) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSchemaDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSchemaDB)(nil).Close))
}

// GetSchemaVersion mocks base method.
func (m *MockSchemaDB) GetSchemaVersion(ctx context.Context) (Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaVersion", ctx)
	ret0, _ := ret[0].(Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemaVersion indicates an expected call of GetSchemaVersion.
func (mr *MockSchemaDBMockRecorder) GetSchemaVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaVersion", reflect.TypeOf((*MockSchemaDB)(nil).GetSchemaVersion), ctx)
}

// HasSchemaVersioning mocks base method.
func (m *MockSchemaDB) HasSchemaVersioning(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSchemaVersioning", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSchemaVersioning indicates an expected call of HasSchemaVersioning.
func (mr *MockSchemaDBMockRecorder) HasSchemaVersioning(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSchemaVersioning", reflect.TypeOf((*MockSchemaDB)(nil).HasSchemaVersioning), ctx)
}

// LatestSchema mocks base method.
func (m *MockSchemaDB) LatestSchema() Schema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestSchema")
	ret0, _ := ret[0].(Schema)
	return ret0
}

// LatestSchema indicates an expected call of LatestSchema.
func (mr *MockSchemaDBMockRecorder) LatestSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestSchema", reflect.TypeOf((*MockSchemaDB)(nil).LatestSchema))
}

// SetupVersioning mocks base method.
func (m *MockSchemaDB) SetupVersioning(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupVersioning", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupVersioning indicates an expected call of SetupVersioning.
func (mr *MockSchemaDBMockRecorder) SetupVersioning(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupVersioning", reflect.TypeOf((*MockSchemaDB)(nil).SetupVersioning), ctx)
}

// UpdateSchema mocks base method.
func (m *MockSchemaDB) UpdateSchema(ctx context.Context, update *SchemaUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchema", ctx, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchema indicates an expected call of UpdateSchema.
func (mr *MockSchemaDBMockRecorder) UpdateSchema(ctx, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchema", reflect.TypeOf((*MockSchemaDB)(nil).UpdateSchema), ctx, update)
}

// MockSchema is a mock of Schema interface.
type MockSchema struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaMockRecorder
	isgomock struct{}
}

// MockSchemaMockRecorder is the mock recorder for MockSchema.
type MockSchemaMockRecorder struct {
	mock *MockSchema
}

// NewMockSchema creates a new mock instance.
func NewMockSchema(ctrl *gomock.Controller) *MockSchema {
	mock := &MockSchema{ctrl: ctrl}
	mock.recorder = &MockSchemaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchema) EXPECT() *MockSchemaMockRecorder {
	return m.recorder
}

// AllUpdates mocks base method.
func (m *MockSchema) AllUpdates() ([]*SchemaUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllUpdates")
	ret0, _ := ret[0].([]*SchemaUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllUpdates indicates an expected call of AllUpdates.
func (mr *MockSchemaMockRecorder) AllUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllUpdates", reflect.TypeOf((*MockSchema)(nil).AllUpdates))
}

// LatestVersion mocks base method.
func (m *MockSchema) LatestVersion() Version {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersion")
	ret0, _ := ret[0].(Version)
	return ret0
}

// LatestVersion indicates an expected call of LatestVersion.
func (mr *MockSchemaMockRecorder) LatestVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersion", reflect.TypeOf((*MockSchema)(nil).LatestVersion))
}

// SkipToLatest mocks base method.
func (m *MockSchema) SkipToLatest() (*SchemaUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkipToLatest")
	ret0, _ := ret[0].(*SchemaUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SkipToLatest indicates an expected call of SkipToLatest.
func (mr *MockSchemaMockRecorder) SkipToLatest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkipToLatest", reflect.TypeOf((*MockSchema)(nil).SkipToLatest))
}
