// Code generated by gowrap. DO NOT EDIT.
// template: ../../../templates/thrift.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package thrift

import (
	context "context"

	matching "github.com/uber/cadence/.gen/go/matching"
	shared "github.com/uber/cadence/.gen/go/shared"
	mapper "github.com/uber/cadence/common/types/mapper/thrift"
)

func (g ThriftHandler) AddActivityTask(ctx context.Context, AddRequest *matching.AddActivityTaskRequest) (err error) {
	_, err = g.h.AddActivityTask(ctx, mapper.ToMatchingAddActivityTaskRequest(AddRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) AddDecisionTask(ctx context.Context, AddRequest *matching.AddDecisionTaskRequest) (err error) {
	_, err = g.h.AddDecisionTask(ctx, mapper.ToMatchingAddDecisionTaskRequest(AddRequest))
	return mapper.FromError(err)
}

func (g ThriftHandler) CancelOutstandingPoll(ctx context.Context, Request *matching.CancelOutstandingPollRequest) (err error) {
	err = g.h.CancelOutstandingPoll(ctx, mapper.ToMatchingCancelOutstandingPollRequest(Request))
	return mapper.FromError(err)
}

func (g ThriftHandler) DescribeTaskList(ctx context.Context, Request *matching.DescribeTaskListRequest) (dp1 *shared.DescribeTaskListResponse, err error) {
	response, err := g.h.DescribeTaskList(ctx, mapper.ToMatchingDescribeTaskListRequest(Request))
	return mapper.FromMatchingDescribeTaskListResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) GetTaskListsByDomain(ctx context.Context, Request *shared.GetTaskListsByDomainRequest) (gp1 *shared.GetTaskListsByDomainResponse, err error) {
	response, err := g.h.GetTaskListsByDomain(ctx, mapper.ToMatchingGetTaskListsByDomainRequest(Request))
	return mapper.FromMatchingGetTaskListsByDomainResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) ListTaskListPartitions(ctx context.Context, Request *matching.ListTaskListPartitionsRequest) (lp1 *shared.ListTaskListPartitionsResponse, err error) {
	response, err := g.h.ListTaskListPartitions(ctx, mapper.ToMatchingListTaskListPartitionsRequest(Request))
	return mapper.FromMatchingListTaskListPartitionsResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) PollForActivityTask(ctx context.Context, PollRequest *matching.PollForActivityTaskRequest) (pp1 *shared.PollForActivityTaskResponse, err error) {
	response, err := g.h.PollForActivityTask(ctx, mapper.ToMatchingPollForActivityTaskRequest(PollRequest))
	return mapper.FromMatchingPollForActivityTaskResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) PollForDecisionTask(ctx context.Context, PollRequest *matching.PollForDecisionTaskRequest) (pp1 *matching.PollForDecisionTaskResponse, err error) {
	response, err := g.h.PollForDecisionTask(ctx, mapper.ToMatchingPollForDecisionTaskRequest(PollRequest))
	return mapper.FromMatchingPollForDecisionTaskResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) QueryWorkflow(ctx context.Context, QueryRequest *matching.QueryWorkflowRequest) (qp1 *shared.QueryWorkflowResponse, err error) {
	response, err := g.h.QueryWorkflow(ctx, mapper.ToMatchingQueryWorkflowRequest(QueryRequest))
	return mapper.FromMatchingQueryWorkflowResponse(response), mapper.FromError(err)
}

func (g ThriftHandler) RespondQueryTaskCompleted(ctx context.Context, Request *matching.RespondQueryTaskCompletedRequest) (err error) {
	err = g.h.RespondQueryTaskCompleted(ctx, mapper.ToMatchingRespondQueryTaskCompletedRequest(Request))
	return mapper.FromError(err)
}
