// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/errorinjector.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package errorinjectors

import (
	"context"
	"time"

	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// injectorHistoryTaskDLQManager implements _sourcePersistence.HistoryTaskDLQManager interface instrumented with error injection.
type injectorHistoryTaskDLQManager struct {
	wrapped   _sourcePersistence.HistoryTaskDLQManager
	starttime time.Time
	errorRate float64
	logger    log.Logger
}

// NewHistoryTaskDLQManager creates a new instance of HistoryTaskDLQManager with error injection.
func NewHistoryTaskDLQManager(
	wrapped persistence.HistoryTaskDLQManager,
	errorRate float64,
	logger log.Logger,
	starttime time.Time,
) persistence.HistoryTaskDLQManager {
	return &injectorHistoryTaskDLQManager{
		wrapped:   wrapped,
		starttime: starttime,
		errorRate: errorRate,
		logger:    logger,
	}
}

func (c *injectorHistoryTaskDLQManager) Close() {
	c.wrapped.Close()
	return
}

func (c *injectorHistoryTaskDLQManager) CreateHistoryDLQAckLevelIfNotExists(ctx context.Context, request _sourcePersistence.CreateHistoryDLQAckLevelRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.CreateHistoryDLQAckLevelIfNotExists(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "HistoryTaskDLQManager.CreateHistoryDLQAckLevelIfNotExists", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorHistoryTaskDLQManager) CreateHistoryDLQTask(ctx context.Context, request _sourcePersistence.CreateHistoryDLQTaskRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.CreateHistoryDLQTask(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "HistoryTaskDLQManager.CreateHistoryDLQTask", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorHistoryTaskDLQManager) DeleteHistoryDLQTasks(ctx context.Context, request _sourcePersistence.HistoryDLQDeleteTasksRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.DeleteHistoryDLQTasks(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "HistoryTaskDLQManager.DeleteHistoryDLQTasks", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorHistoryTaskDLQManager) GetHistoryDLQAckLevels(ctx context.Context, request _sourcePersistence.HistoryDLQGetAckLevelsRequest) (ha1 []_sourcePersistence.HistoryDLQAckLevel, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		ha1, err = c.wrapped.GetHistoryDLQAckLevels(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "HistoryTaskDLQManager.GetHistoryDLQAckLevels", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorHistoryTaskDLQManager) GetHistoryDLQTasks(ctx context.Context, request _sourcePersistence.HistoryDLQGetTasksRequest) (h1 _sourcePersistence.HistoryDLQGetTasksResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		h1, err = c.wrapped.GetHistoryDLQTasks(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "HistoryTaskDLQManager.GetHistoryDLQTasks", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorHistoryTaskDLQManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *injectorHistoryTaskDLQManager) UpdateHistoryDLQAckLevel(ctx context.Context, request _sourcePersistence.HistoryDLQUpdateAckLevelRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.UpdateHistoryDLQAckLevel(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "HistoryTaskDLQManager.UpdateHistoryDLQAckLevel", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}
