// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/errorinjector.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package errorinjectors

import (
	"context"
	"time"

	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// injectorQueueManager implements _sourcePersistence.QueueManager interface instrumented with error injection.
type injectorQueueManager struct {
	wrapped   _sourcePersistence.QueueManager
	starttime time.Time
	errorRate float64
	logger    log.Logger
}

// NewQueueManager creates a new instance of QueueManager with error injection.
func NewQueueManager(
	wrapped persistence.QueueManager,
	errorRate float64,
	logger log.Logger,
	starttime time.Time,
) persistence.QueueManager {
	return &injectorQueueManager{
		wrapped:   wrapped,
		starttime: starttime,
		errorRate: errorRate,
		logger:    logger,
	}
}

func (c *injectorQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *injectorQueueManager) DeleteMessageFromDLQ(ctx context.Context, request *_sourcePersistence.DeleteMessageFromDLQRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.DeleteMessageFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.DeleteMessageFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) DeleteMessagesBefore(ctx context.Context, request *_sourcePersistence.DeleteMessagesBeforeRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.DeleteMessagesBefore(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.DeleteMessagesBefore", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) EnqueueMessage(ctx context.Context, request *_sourcePersistence.EnqueueMessageRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.EnqueueMessage(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.EnqueueMessage", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) EnqueueMessageToDLQ(ctx context.Context, request *_sourcePersistence.EnqueueMessageToDLQRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.EnqueueMessageToDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.EnqueueMessageToDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) GetAckLevels(ctx context.Context, request *_sourcePersistence.GetAckLevelsRequest) (gp1 *_sourcePersistence.GetAckLevelsResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetAckLevels(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.GetAckLevels", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) GetDLQAckLevels(ctx context.Context, request *_sourcePersistence.GetDLQAckLevelsRequest) (gp1 *_sourcePersistence.GetDLQAckLevelsResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetDLQAckLevels(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.GetDLQAckLevels", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) GetDLQSize(ctx context.Context, request *_sourcePersistence.GetDLQSizeRequest) (gp1 *_sourcePersistence.GetDLQSizeResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		gp1, err = c.wrapped.GetDLQSize(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.GetDLQSize", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.RangeDeleteMessagesFromDLQRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.RangeDeleteMessagesFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) ReadMessages(ctx context.Context, request *_sourcePersistence.ReadMessagesRequest) (rp1 *_sourcePersistence.ReadMessagesResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		rp1, err = c.wrapped.ReadMessages(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.ReadMessages", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *_sourcePersistence.ReadMessagesFromDLQRequest) (rp1 *_sourcePersistence.ReadMessagesFromDLQResponse, err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		rp1, err = c.wrapped.ReadMessagesFromDLQ(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.ReadMessagesFromDLQ", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) UpdateAckLevel(ctx context.Context, request *_sourcePersistence.UpdateAckLevelRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.UpdateAckLevel(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.UpdateAckLevel", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}

func (c *injectorQueueManager) UpdateDLQAckLevel(ctx context.Context, request *_sourcePersistence.UpdateDLQAckLevelRequest) (err error) {
	fakeErr := generateFakeError(c.errorRate, c.starttime)
	var forwardCall bool
	if forwardCall = shouldForwardCallToPersistence(fakeErr); forwardCall {
		err = c.wrapped.UpdateDLQAckLevel(ctx, request)
	}

	if fakeErr != nil {
		logErr(c.logger, "QueueManager.UpdateDLQAckLevel", fakeErr, forwardCall, err)
		err = fakeErr
		return
	}
	return
}
